/*
Déclencheur permettant d'empêcher la suppression de donnée dans la table TEMP_CORRECTION_PROJET_A_RELATION_TRONCON_VOIE
*/

CREATE OR REPLACE TRIGGER BDXX_TEMP_CORRECTION_PROJET_A_RELATION_TRONCON_VOIE_NO_DELETE
BEFORE DELETE ON G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_RELATION_TRONCON_VOIE
FOR EACH ROW
DECLARE
BEGIN
    RAISE_APPLICATION_ERROR(-20001, 'Il est interdit de supprimer les objets de la table G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_RELATION_TRONCON_VOIE.');
END;

/

