/*
Déclencheur permettant d'empêcher la suppression de donnée dans la table TEMP_CORRECTION_PROJET_A_TRONCON
*/

CREATE OR REPLACE TRIGGER BDXX_TEMP_CORRECTION_PROJET_A_TRONCON_NO_DELETE
BEFORE DELETE ON G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_TRONCON
FOR EACH ROW
DECLARE
BEGIN
    RAISE_APPLICATION_ERROR(-20001, 'Il est interdit de supprimer les objets de la table G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_TRONCON.');
END;

/

