/*
SEQ_TA_RELATION_VOIE_PHYSIQUE_ADMINISTRATIVE_OBJECTID : création de la séquence d'auto-incrémentation de la clé primaire de la table TA_RELATION_VOIE_PHYSIQUE_ADMINISTRATIVE
*/

CREATE SEQUENCE SEQ_TA_RELATION_VOIE_PHYSIQUE_ADMINISTRATIVE_OBJECTID START WITH 1 INCREMENT BY 1;

/

