/*
SEQ_TA_VOIE_SUPRA_COMMUNALE_OBJECTID : création de la séquence d'auto-incrémentation de la clé primaire de la table TA_VOIE_SUPRA_COMMUNALE
*/

CREATE SEQUENCE SEQ_TA_VOIE_SUPRA_COMMUNALE_OBJECTID START WITH 1 INCREMENT BY 1;

/

