/*
SEQ_TA_VOIE_ADMINISTRATIVE_OBJECTID : création de la séquence d'auto-incrémentation de la clé primaire de la table TA_VOIE_ADMINISTRATIVE
*/

CREATE SEQUENCE SEQ_TA_VOIE_ADMINISTRATIVE_OBJECTID START WITH 1 INCREMENT BY 1;

/

