/*
Création de la VM VM_VOIE_PHYSIQUE_MATERIALISEE_NON_REORIENTEE matérialisant la géométrie des voies administrative.
*/
-- 1. Suppression de la VM et de ses métadonnées
/*DROP MATERIALIZED VIEW G_BASE_VOIE.VM_VOIE_PHYSIQUE_MATERIALISEE_NON_REORIENTEE;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'VM_VOIE_PHYSIQUE_MATERIALISEE_NON_REORIENTEE';
COMMIT;
*/
-- 2. Création de la VM
CREATE MATERIALIZED VIEW "G_BASE_VOIE"."VM_VOIE_PHYSIQUE_MATERIALISEE_NON_REORIENTEE" ("ID_VOIE_PHYSIQUE", "GEOM")        
REFRESH FORCE
START WITH TO_DATE('06-04-2023 16:00:00', 'dd-mm-yyyy hh24:mi:ss')
NEXT sysdate + 120/24/1440
DISABLE QUERY REWRITE AS
SELECT
    b.objectid AS id_voie_physique,
    SDO_AGGR_UNION(
        SDOAGGRTYPE(a.geom , 0.005)
    ) AS geom
FROM
    G_BASE_VOIE.TA_TRONCON a
    INNER JOIN G_BASE_VOIE.TA_VOIE_PHYSIQUE b ON b.objectid = a.fid_voie_physique
GROUP BY
    b.objectid;

-- 3. Création des commentaires de la VM
COMMENT ON MATERIALIZED VIEW G_BASE_VOIE.VM_VOIE_PHYSIQUE_MATERIALISEE_NON_REORIENTEE IS 'Vue matérialisée matérialisant la géométrie des voies physiques.';

-- 4. Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'VM_VOIE_PHYSIQUE_MATERIALISEE_NON_REORIENTEE',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005)), 
    2154
);
COMMIT;

-- 5. Création de la clé primaire
ALTER MATERIALIZED VIEW VM_VOIE_PHYSIQUE_MATERIALISEE_NON_REORIENTEE 
ADD CONSTRAINT VM_VOIE_PHYSIQUE_MATERIALISEE_NON_REORIENTEE_PK 
PRIMARY KEY (ID_VOIE_PHYSIQUE);

-- 6. Création des index
CREATE INDEX VM_VOIE_PHYSIQUE_MATERIALISEE_NON_REORIENTEE_SIDX
ON G_BASE_VOIE.VM_VOIE_PHYSIQUE_MATERIALISEE_NON_REORIENTEE(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS(
  'sdo_indx_dims=2, 
  layer_gtype=MULTILINE, 
  tablespace=G_ADT_INDX, 
  work_tablespace=DATA_TEMP'
);

-- 7. Affectations des droits
GRANT SELECT ON G_BASE_VOIE.VM_VOIE_PHYSIQUE_MATERIALISEE_NON_REORIENTEE TO G_ADMIN_SIG;

/

