/*
Création de la VM regroupant les centroïds des voies physiques, partageant anciennement le même tronçon. 
*/
/*
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_TEMP_C_CENTROID_VOIE_PHYSIQUE;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME IS 'VM_TEMP_C_CENTROID_VOIE_PHYSIQUE';
COMMIT;
*/

CREATE MATERIALIZED VIEW "G_BASE_VOIE"."VM_TEMP_C_CENTROID_VOIE_PHYSIQUE" ("ID_VOIE_PHYSIQUE","GEOM")        
REFRESH ON DEMAND
FORCE
DISABLE QUERY REWRITE AS
SELECT
    a.id_voie_physique,
    SDO_CS.MAKE_2D(
        SDO_LRS.LOCATE_PT(
            SDO_LRS.CONVERT_TO_LRS_GEOM(a.geom, m.diminfo),
            SDO_LRS.GEOM_SEGMENT_END_MEASURE(SDO_LRS.CONVERT_TO_LRS_GEOM(a.geom, m.diminfo))/2
        ),
        2154
    ) AS geom
FROM
    G_BASE_VOIE.VM_TEMP_C_VOIE_PHYSIQUE a,
    USER_SDO_GEOM_METADATA m
WHERE
    m.table_name = 'VM_TEMP_C_VOIE_PHYSIQUE';
    
-- 3. Création des commentaires de la VM
COMMENT ON MATERIALIZED VIEW G_BASE_VOIE.VM_TEMP_C_CENTROID_VOIE_PHYSIQUE IS 'VM matérialisant les centroïds des voies physiques.';
COMMENT ON COLUMN G_BASE_VOIE.VM_TEMP_C_CENTROID_VOIE_PHYSIQUE.ID_VOIE_PHYSIQUE IS 'Identifiant de la voie physique présente dans VM_TEMP_C_VOIE_PHYSIQUE.';
COMMENT ON COLUMN G_BASE_VOIE.VM_TEMP_C_CENTROID_VOIE_PHYSIQUE.GEOM IS 'Géométrie de type point.';

-- 4. Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'VM_TEMP_C_CENTROID_VOIE_PHYSIQUE',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005)), 
    2154
);
COMMIT;

-- 5. Création de la clé primaire
ALTER MATERIALIZED VIEW VM_TEMP_C_CENTROID_VOIE_PHYSIQUE 
ADD CONSTRAINT VM_TEMP_C_CENTROID_VOIE_PHYSIQUE_PK 
PRIMARY KEY (ID_VOIE_PHYSIQUE);

-- 6. Création des index
CREATE INDEX VM_TEMP_C_CENTROID_VOIE_PHYSIQUE_SIDX
ON G_BASE_VOIE.VM_TEMP_C_CENTROID_VOIE_PHYSIQUE(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
PARAMETERS(
  'sdo_indx_dims=2, 
  layer_gtype=POINT, 
  tablespace=G_ADT_INDX, 
  work_tablespace=DATA_TEMP'
);

-- 7. Affectations des droits
GRANT SELECT ON G_BASE_VOIE.VM_TEMP_C_CENTROID_VOIE_PHYSIQUE TO G_ADMIN_SIG;

/

