/*
Création de la vue matérialisée VM_ADRESSE_LITTERALIS regroupant, au format LITTERALIS, toutes les adresses de la base présentes
dans les tables TEMP_ADRESSE_CORRECTE_LITTERALIS, TEMP_ADRESSE_DOUBLON_VOIE_LITTERALIS, TEMP_ADRESSE_DOUBLON_DOMANIA_LITTERALIS, TEMP_ADRESSE_AUTRES_LITTERALIS.
Cette VM est utilisée pour exporter les données pour le prestataire Sogelink.
*/

-- 1. Suppression de la VM et de ses métadonnées
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_ADRESSE_LITTERALIS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'VM_ADRESSE_LITTERALIS';
COMMIT;

-- 2. Création de la VM
CREATE MATERIALIZED VIEW "G_BASE_VOIE"."VM_ADRESSE_LITTERALIS" ("CODE_VOIE", "CODE_POINT", "NATURE", "LIBELLE", "NUMERO", "REPETITION", "COTE", "GEOMETRY")        
REFRESH ON DEMAND
FORCE
DISABLE QUERY REWRITE AS
SELECT
    CODE_VOIE,CODE_POINT,NATURE,LIBELLE,NUMERO,CAST(REPETITION AS VARCHAR2(10)) AS REPETITION,COTE,GEOMETRY
FROM
    G_BASE_VOIE.TEMP_ADRESSE_DOUBLON_VOIE_LITTERALIS
WHERE
    code_point NOT IN('213073', '333311', '290440', '290374')
UNION ALL
SELECT
    CODE_VOIE,CODE_POINT,NATURE,LIBELLE,NUMERO,CAST(REPETITION AS VARCHAR2(10)) AS REPETITION,COTE,GEOMETRY
FROM
    G_BASE_VOIE.TEMP_ADRESSE_CORRECTE_LITTERALIS
WHERE
    code_point NOT IN('331519','299591','332914','181776')
UNION ALL
SELECT
    CODE_VOIE,CODE_POINT,NATURE,LIBELLE,NUMERO,CAST(REPETITION AS VARCHAR2(10)) AS REPETITION,COTE,GEOMETRY
FROM
    G_BASE_VOIE.TEMP_ADRESSE_DOUBLON_DOMANIA_LITTERALIS
UNION ALL
SELECT
    CODE_VOIE,CODE_POINT,NATURE,LIBELLE,NUMERO,CAST(REPETITION AS VARCHAR2(10)) AS REPETITION,COTE,GEOMETRY
FROM
    G_BASE_VOIE.TEMP_ADRESSE_AUTRES_LITTERALIS;

-- 3. Création des commentaires de la VM
COMMENT ON MATERIALIZED VIEW G_BASE_VOIE.VM_ADRESSE_LITTERALIS IS 'Vue matérialisée rassemblant toutes les adresses au format LITTERALIS. Cette VM est utilisée pour exporter les données pour le projet LITTERALIS mené par le service voirie et le prestataire SOGELINK';

-- 2. Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'VM_ADRESSE_LITTERALIS',
    'GEOMETRY',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 594000, 964000, 0.005),SDO_DIM_ELEMENT('Y', 6987000, 7165000, 0.005)), 
    2154
);
COMMIT;

-- 3. Création de la clé primaire
ALTER MATERIALIZED VIEW VM_ADRESSE_LITTERALIS 
ADD CONSTRAINT VM_ADRESSE_LITTERALIS_PK 
PRIMARY KEY (CODE_POINT);

-- 4. Création de l'index spatial
CREATE INDEX VM_ADRESSE_LITTERALIS_SIDX
ON G_BASE_VOIE.VM_ADRESSE_LITTERALIS(GEOMETRY)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
PARAMETERS(
  'sdo_indx_dims=2, 
  layer_gtype=POINT, 
  tablespace=G_ADT_INDX, 
  work_tablespace=DATA_TEMP'
);

-- 5. Affectations des droits
GRANT SELECT ON G_BASE_VOIE.VM_ADRESSE_LITTERALIS TO G_ADMIN_SIG;