/*
Création de la VM VM_TRAVAIL_VOIE_AGGREGEE_CODE_INSEE permettant de récupérer la géométrie et le code INSEE de chaque voie.
*/

CREATE MATERIALIZED VIEW "G_BASE_VOIE"."VM_TRAVAIL_VOIE_AGGREGEE_CODE_INSEE" ("ID_VOIE","TYPE_DE_VOIE","LIBELLE_VOIE","COMPLEMENT_NOM_VOIE", "CODE_INSEE", "GEOM")        
REFRESH ON DEMAND
FORCE
DISABLE QUERY REWRITE AS
SELECT
    id_voie,
    type_de_voie,
    libelle_voie,
    complement_nom_voie,
    TRIM(GET_CODE_INSEE_97_COMMUNES_TRONCON('VM_VOIE_AGGREGEE', geom)) AS code_insee,
    geom
FROM
    G_BASE_VOIE.VM_VOIE_AGGREGEE;
    
-- 3. Création des commentaires de la VM
COMMENT ON MATERIALIZED VIEW G_BASE_VOIE.VM_TRAVAIL_VOIE_AGGREGEE_CODE_INSEE IS 'Vue matérialisée de travail permettant de récupérer le code insee et la géométrie des voies.';

-- 4. Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'VM_TRAVAIL_VOIE_AGGREGEE_CODE_INSEE',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 594000, 964000, 0.005),SDO_DIM_ELEMENT('Y', 6987000, 7165000, 0.005)), 
    2154
);
COMMIT;

-- 5. Création de la clé primaire
ALTER MATERIALIZED VIEW VM_TRAVAIL_VOIE_AGGREGEE_CODE_INSEE 
ADD CONSTRAINT VM_TRAVAIL_VOIE_AGGREGEE_CODE_INSEE_PK 
PRIMARY KEY (ID_VOIE);

-- 6. Création des index
CREATE INDEX VM_TRAVAIL_VOIE_AGGREGEE_CODE_INSEE_SIDX
ON G_BASE_VOIE.VM_TRAVAIL_VOIE_AGGREGEE_CODE_INSEE(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
PARAMETERS(
  'sdo_indx_dims=2, 
  layer_gtype=MULTILINE, 
  tablespace=G_ADT_INDX, 
  work_tablespace=DATA_TEMP'
);

CREATE INDEX VM_TRAVAIL_VOIE_AGGREGEE_CODE_INSEE_IDX ON G_BASE_VOIE.VM_TRAVAIL_VOIE_AGGREGEE_CODE_INSEE(CODE_INSEE, TYPE_DE_VOIE, LIBELLE_VOIE, COMPLEMENT_NOM_VOIE)
    TABLESPACE G_ADT_INDX;

-- 7. Affectations des droits
GRANT SELECT ON G_BASE_VOIE.VM_TRAVAIL_VOIE_AGGREGEE_CODE_INSEE TO G_ADMIN_SIG;

/

