/*
Création des droits de lecture et de mise à jour des objets du projet LITTERALIS présents sur le schéma G_BASE_VOIE
*/

-- Tables
GRANT SELECT ON G_BASE_VOIE.TA_SECTEUR_VOIRIE TO G_BASE_VOIE_LEC;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_BASE_VOIE.TA_SECTEUR_VOIRIE TO G_BASE_VOIE_MAJ;

-- Vues
GRANT SELECT ON G_BASE_VOIE.V_LITTERALIS_AUDIT_TRONCON TO G_BASE_VOIE_LEC;
GRANT SELECT ON G_BASE_VOIE.V_LITTERALIS_AUDIT_ADRESSE TO G_BASE_VOIE_LEC;
GRANT SELECT ON G_BASE_VOIE.V_LITTERALIS_AUDIT_ZONE_PARTICULIERE TO G_BASE_VOIE_LEC;
GRANT SELECT ON G_BASE_VOIE.V_LITTERALIS_TRONCON TO G_BASE_VOIE_LEC;
GRANT SELECT ON G_BASE_VOIE.V_LITTERALIS_ADRESSE TO G_BASE_VOIE_LEC;
GRANT SELECT ON G_BASE_VOIE.V_LITTERALIS_REGROUPEMENT TO G_BASE_VOIE_LEC;
GRANT SELECT ON G_BASE_VOIE.V_LITTERALIS_ZONE_PARTICULIERE TO G_BASE_VOIE_LEC;

-- Vues matérialisées
GRANT SELECT ON G_BASE_VOIE.VM_TAMPON_LITTERALIS_CORRESPONDANCE_DOMANIALITE_CLASSEMENT TO G_BASE_VOIE_LEC;
GRANT SELECT ON G_BASE_VOIE.VM_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE TO G_BASE_VOIE_LEC;
GRANT SELECT ON G_BASE_VOIE.VM_TAMPON_LITTERALIS_TRONCON TO G_BASE_VOIE_LEC;
GRANT SELECT ON G_BASE_VOIE.VM_TAMPON_LITTERALIS_ADRESSE TO G_BASE_VOIE_LEC;
GRANT SELECT ON G_BASE_VOIE.VM_TERRITOIRE_VOIRIE TO G_BASE_VOIE_LEC;
GRANT SELECT ON G_BASE_VOIE.VM_UNITE_TERRITORIALE_VOIRIE TO G_BASE_VOIE_LEC;
GRANT SELECT ON G_BASE_VOIE.VM_TAMPON_LITTERALIS_REGROUPEMENT TO G_BASE_VOIE_LEC;
GRANT SELECT ON G_BASE_VOIE.VM_TAMPON_LITTERALIS_ZONE_AGGLOMERATION TO G_BASE_VOIE_LEC;
GRANT SELECT ON G_BASE_VOIE.VM_TAMPON_LITTERALIS_ZONE_PARTICULIERE_EN_AGGLO TO G_BASE_VOIE_LEC;
GRANT SELECT ON G_BASE_VOIE.VM_TAMPON_LITTERALIS_ZONE_PARTICULIERE_HORS_AGGLO TO G_BASE_VOIE_LEC;
GRANT SELECT ON G_BASE_VOIE.VM_TAMPON_LITTERALIS_ZONE_PARTICULIERE_INTERSECT_AGGLO TO G_BASE_VOIE_LEC;
GRANT SELECT ON G_BASE_VOIE.VM_TAMPON_LITTERALIS_ZONE_PARTICULIERE_INTERSECT_HORS_AGGLO TO G_BASE_VOIE_LEC;
GRANT SELECT ON G_BASE_VOIE.VM_INFORMATION_VOIE_LITTERALIS TO G_BASE_VOIE_LEC;

/

