/*
Affectation des droits de lecture et de référence vers le schéma G_GEO pour les métadonnées et les Familles/Libellés.
*/

GRANT REFERENCES ON G_GEO.TA_METADONNEE TO G_BASE_VOIE;

/

GRANT REFERENCES ON G_GEO.TA_LIBELLE_LONG TO G_BASE_VOIE;

/

GRANT REFERENCES ON G_GEO.TA_FAMILLE_LIBELLE TO G_BASE_VOIE;

/

GRANT REFERENCES ON G_GEO.TA_FAMILLE TO G_BASE_VOIE;

/

GRANT SELECT ON G_GEO.TA_METADONNEE TO G_BASE_VOIE WITH GRANT OPTION;

/

GRANT SELECT ON G_GEO.TA_LIBELLE_LONG TO G_BASE_VOIE WITH GRANT OPTION;

/

GRANT SELECT ON G_GEO.TA_FAMILLE TO G_BASE_VOIE WITH GRANT OPTION;

/

GRANT SELECT ON G_GEO.TA_FAMILLE_LIBELLE TO G_BASE_VOIE WITH GRANT OPTION;

/

GRANT SELECT ON G_GEO.TA_SOURCE TO G_BASE_VOIE;

/

GRANT SELECT ON G_GEO.TA_PROVENANCE TO G_BASE_VOIE;

/

GRANT SELECT ON G_GEO.TA_DATE_ACQUISITION TO G_BASE_VOIE;

/

GRANT SELECT ON G_GEO.TA_METADONNEE_RELATION_ORGANISME TO G_BASE_VOIE;

/

GRANT SELECT ON G_GEO.TA_ORGANISME TO G_BASE_VOIE;

/