GRANT REFERENCES ON G_GEO.TA_METADONNEE TO G_BASE_VOIE;

/

GRANT REFERENCES ON G_GEO.TA_LIBELLE TO G_BASE_VOIE;

/

GRANT SELECT ON G_GEO.TA_METADONNEE TO G_BASE_VOIE WITH GRANT OPTION;

/

GRANT SELECT ON G_GEO.TA_LIBELLE TO G_BASE_VOIE WITH GRANT OPTION;

/

GRANT SELECT ON G_GEO.TA_FAMILLE TO G_BASE_VOIE WITH GRANT OPTION;

/
