/*
Création des droits de lecture et de mise à jour des objets du schéma G_BASE_VOIE
*/

-- G_BASE_VOIE_R (Lecture Seule) :
-- Tables
GRANT SELECT ON G_BASE_VOIE.TA_AGENT TO G_BASE_VOIE_R;
GRANT SELECT ON G_BASE_VOIE.TA_INFOS_SEUIL TO G_BASE_VOIE_R;
GRANT SELECT ON G_BASE_VOIE.TA_RIVOLI TO G_BASE_VOIE_R;
GRANT SELECT ON G_BASE_VOIE.TA_SEUIL TO G_BASE_VOIE_R;
GRANT SELECT ON G_BASE_VOIE.TA_TRONCON TO G_BASE_VOIE_R;
GRANT SELECT ON G_BASE_VOIE.TA_TYPE_VOIE TO G_BASE_VOIE_R;
GRANT SELECT ON G_BASE_VOIE.TA_VOIE TO G_BASE_VOIE_R;
GRANT SELECT ON G_BASE_VOIE.TA_HIERARCHISATION_VOIE TO G_BASE_VOIE_R;

-- Vues
GRANT SELECT ON G_BASE_VOIE.V_TRONCON_VOIE TO G_BASE_VOIE_R;
GRANT SELECT ON G_BASE_VOIE.V_BAL_95_COMMUNES_GEOM TO G_BASE_VOIE_R;

-- Vues matérialisées
GRANT SELECT ON G_BASE_VOIE.VM_GRU_ADRESSE TO G_BASE_VOIE_R;
GRANT SELECT ON G_BASE_VOIE.VM_VOIE_AGGREGEE TO G_BASE_VOIE_R;

-- G_BASE_VOIE_RW (Mise à jour) :
GRANT SELECT, INSERT, UPDATE, DELETE ON G_BASE_VOIE.TA_AGENT TO G_BASE_VOIE_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_BASE_VOIE.TA_INFOS_SEUIL TO G_BASE_VOIE_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_BASE_VOIE.TA_RIVOLI TO G_BASE_VOIE_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_BASE_VOIE.TA_SEUIL TO G_BASE_VOIE_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_BASE_VOIE.TA_TRONCON TO G_BASE_VOIE_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_BASE_VOIE.TA_TYPE_VOIE TO G_BASE_VOIE_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_BASE_VOIE.TA_VOIE TO G_BASE_VOIE_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON G_BASE_VOIE.TA_HIERARCHISATION_VOIE TO G_BASE_VOIE_RW;

-- Codes à lancer depuis G_BASE_VOIE_RW
GRANT SELECT ON G_BASE_VOIE.V_TRONCON_VOIE TO SIREO_LEC;

/

