/*
Création des droits de lecture et de mise à jour des objets transitoires du schéma G_BASE_VOIE
*/
SET SERVEROUTPUT ON
DECLARE
	v_nom_sequence VARCHAR2(200 BYTE);
BEGIN
	SAVEPOINT POINT_CREATION_DROITS;

	-- G_BASE_VOIE_R (Lecture Seule) :
	-- Tables
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_BASE_VOIE.TEMP_AGENT TO G_BASE_VOIE_R';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_BASE_VOIE.TEMP_TRONCON TO G_BASE_VOIE_R';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_BASE_VOIE.TEMP_TYPE_VOIE TO G_BASE_VOIE_R';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_BASE_VOIE.TEMP_VOIE TO G_BASE_VOIE_R';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_BASE_VOIE.TEMP_RELATION_TRONCON_VOIE TO G_BASE_VOIE_R';

	-- Séquences
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_BASE_VOIE.SEQ_TEMP_TRONCON_OBJECTID TO G_BASE_VOIE_R';

	-- Vues
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_BASE_VOIE.V_TEMP_RELATION_TRONCON_VOIE_DOUBLON TO G_BASE_VOIE_R';

	-- Vues matérialisées
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_BASE_VOIE.VM_TEMP_VOIE_AGGREGEE TO G_BASE_VOIE_R';

	-- G_BASE_VOIE_RW (Mise à jour) :
	-- Tables
	EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON G_BASE_VOIE.TEMP_TRONCON TO G_BASE_VOIE_RW';
	EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON G_BASE_VOIE.TEMP_TYPE_VOIE TO G_BASE_VOIE_RW';
	EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON G_BASE_VOIE.TEMP_VOIE TO G_BASE_VOIE_RW';
	EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON G_BASE_VOIE.TEMP_RELATION_TRONCON_VOIE TO G_BASE_VOIE_RW';

	-- Vues
	EXECUTE IMMEDIATE 'GRANT SELECT, UPDATE, DELETE ON G_BASE_VOIE.V_TEMP_RELATION_TRONCON_VOIE_DOUBLON TO G_BASE_VOIE_RW';

	-- Séquences
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_BASE_VOIE.SEQ_TEMP_TRONCON_OBJECTID TO G_BASE_VOIE_RW';

	SELECT
	    s.NAME INTO v_nom_sequence
	FROM
	   sys.IDNSEQ$ os
	   INNER JOIN sys.obj$ t ON (t.obj# = os.obj#)
	   INNER JOIN sys.obj$ s ON (s.obj# = os.seqobj#)
	   INNER JOIN sys.col$ c ON (c.obj# = t.obj# AND c.col# = os.intcol#)
	   INNER JOIN all_users u ON (u.user_id = t.owner#)
	WHERE t.NAME = 'TEMP_TYPE_VOIE'
	AND u.username = 'G_BASE_VOIE';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_BASE_VOIE.'||v_nom_sequence||' TO G_BASE_VOIE_RW';

	SELECT
	    s.NAME INTO v_nom_sequence
	FROM
	   sys.IDNSEQ$ os
	   INNER JOIN sys.obj$ t ON (t.obj# = os.obj#)
	   INNER JOIN sys.obj$ s ON (s.obj# = os.seqobj#)
	   INNER JOIN sys.col$ c ON (c.obj# = t.obj# AND c.col# = os.intcol#)
	   INNER JOIN all_users u ON (u.user_id = t.owner#)
	WHERE t.NAME = 'TEMP_RELATION_TRONCON_VOIE'
	AND u.username = 'G_BASE_VOIE';
	EXECUTE IMMEDIATE 'GRANT SELECT ON G_BASE_VOIE.'||v_nom_sequence||' TO G_BASE_VOIE_RW';

	-- En cas d'erreur une exception est levée et un rollback effectué, empêchant ainsi toute insertion de se faire et de retourner à l'état des tables précédent l'insertion.
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('L''erreur ' || SQLCODE || 'est survenue. Un rollback a été effectué : ' || SQLERRM(SQLCODE));
            ROLLBACK TO POINT_CREATION_DROITS;
END;

/

