/*
Affectation des droits de lecture et de mise à jour aux vues
*/

GRANT SELECT ON G_BASE_VOIE.V_STAT_NOMBRE_OBJET TO G_BASE_VOIE_LEC;
GRANT SELECT ON G_BASE_VOIE.V_STAT_NOMBRE_VOIE_ADMINISTRATIVE_PAR_COMMUNE TO G_BASE_VOIE_LEC;
GRANT SELECT ON G_BASE_VOIE.V_STAT_NOMBRE_VOIE_ADMINISTRATIVE_PAR_NOMBRE_VOIE_PHYSIQUE TO G_BASE_VOIE_LEC;
GRANT SELECT ON G_BASE_VOIE.V_STAT_NOMBRE_VOIE_PHYSIQUE_PAR_VOIE_ADMINISTRATIVE TO G_BASE_VOIE_LEC;
GRANT SELECT ON G_BASE_VOIE.V_STAT_NOMBRE_SEUIL_PAR_GEOMETRIE TO G_BASE_VOIE_LEC;
GRANT SELECT ON G_BASE_VOIE.V_STAT_CREATION_OBJET_PAR_ANNEE_MOIS TO G_BASE_VOIE_LEC;

/

