
-- Création des droits de lecture pour le schéma G_BASE_VOIE_LEC et SIREO_LEC sur G_BASE_VOIE.

-- Codes à lancer depuis G_BASE_VOIE
GRANT SELECT ON G_BASE_VOIE.V_TRONCON_LITTERALIS TO G_BASE_VOIE_LEC WITH GRANT OPTION;
GRANT SELECT ON G_BASE_VOIE.V_ADRESSE_LITTERALIS TO G_BASE_VOIE_LEC WITH GRANT OPTION;
GRANT SELECT ON G_BASE_VOIE.V_REGROUPEMENT_LITTERALIS TO G_BASE_VOIE_LEC WITH GRANT OPTION;
GRANT SELECT ON G_BASE_VOIE.V_TRONCON_VOIE TO G_BASE_VOIE_LEC WITH GRANT OPTION;
GRANT SELECT ON G_BASE_VOIE.TA_AGENT TO G_BASE_VOIE_LEC WITH GRANT OPTION;
GRANT SELECT ON G_BASE_VOIE.TA_FAMILLE TO G_BASE_VOIE_LEC WITH GRANT OPTION;
GRANT SELECT ON G_BASE_VOIE.TA_INFOS_SEUIL TO G_BASE_VOIE_LEC WITH GRANT OPTION;
GRANT SELECT ON G_BASE_VOIE.TA_LIBELLE TO G_BASE_VOIE_LEC WITH GRANT OPTION;
GRANT SELECT ON G_BASE_VOIE.TA_RELATION_FAMILLE_LIBELLE TO G_BASE_VOIE_LEC WITH GRANT OPTION;
GRANT SELECT ON G_BASE_VOIE.TA_RELATION_TRONCON_SEUIL TO G_BASE_VOIE_LEC WITH GRANT OPTION;
GRANT SELECT ON G_BASE_VOIE.TA_RELATION_TRONCON_VOIE TO G_BASE_VOIE_LEC WITH GRANT OPTION;
GRANT SELECT ON G_BASE_VOIE.TA_RIVOLI TO G_BASE_VOIE_LEC WITH GRANT OPTION;
GRANT SELECT ON G_BASE_VOIE.TA_SEUIL TO G_BASE_VOIE_LEC WITH GRANT OPTION;
GRANT SELECT ON G_BASE_VOIE.TA_TRONCON TO G_BASE_VOIE_LEC WITH GRANT OPTION;
GRANT SELECT ON G_BASE_VOIE.TA_TYPE_VOIE TO G_BASE_VOIE_LEC WITH GRANT OPTION;
GRANT SELECT ON G_BASE_VOIE.TA_VOIE TO G_BASE_VOIE_LEC WITH GRANT OPTION;

-- Codes à lancer depuis G_BASE_VOIE_LEC
GRANT SELECT ON G_BASE_VOIE.V_TRONCON_VOIE TO SIREO_LEC;

/
