/*
Suppression des tables de la structure tampon du projet LITTERALIS.
*/

-- 1. Suppression des tables/VM temporaires
DROP TABLE G_BASE_VOIE.TA_TAMPON_LITTERALIS_CORRESPONDANCE_DOMANIALITE_CLASSEMENT CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_TAMPON_LITTERALIS_TRONCON CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_TAMPON_LITTERALIS_ADRESSE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_TAMPON_LITTERALIS_VOIE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_TAMPON_LITTERALIS_ZONE_PARTICULIERE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_TAMPON_LITTERALIS_SECTEUR CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_TAMPON_LITTERALIS_TERRITOIRE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_TAMPON_LITTERALIS_UNITE_TERRITORIALE CASCADE CONSTRAINTS;

-- 2. Suppression des métadonnées spatiales des tables temporaires
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_TAMPON_LITTERALIS_TRONCON';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_TAMPON_LITTERALIS_ADRESSE';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_TAMPON_LITTERALIS_VOIE';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_TAMPON_LITTERALIS_ZONE_PARTICULIERE';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_TAMPON_LITTERALIS_SECTEUR';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_TAMPON_LITTERALIS_TERRITOIRE';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_TAMPON_LITTERALIS_UNITE_TERRITORIALE';
COMMIT;