/*
La table TEMP_A_LIBELLE_VOIE regroupe tous les informations de chaque voie de la base voie. Cette séparation de l'identifiant de voie permet d''affecter deux noms à une voie physique.
*/

-- 1. Création de la table TEMP_A_LIBELLE_VOIE
CREATE TABLE G_BASE_VOIE.TEMP_A_LIBELLE_VOIE(
    objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
    libelle_voie VARCHAR2(1000 BYTE),
    complement_nom_voie VARCHAR2(100),
    lateralite CHAR(2 BYTE),
    code_insee VARCHAR2(8),
    date_saisie DATE,
    date_modification DATE,
    fid_pnom_saisie NUMBER(38,0),
    fid_pnom_modification NUMBER(38,0),
    fid_voie NUMBER(38,0),
    fid_type_voie NUMBER(38,0)
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE G_BASE_VOIE.TEMP_A_LIBELLE_VOIE IS 'Table rassemblant les informations de chaque voie et notamment leurs libellés : une voie physique peut avoir deux noms différents si elle traverse deux communes différentes.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_A_LIBELLE_VOIE.objectid IS 'Clé primaire auto-incrémentée de la table. Elle remplace l''ancien identifiant ccomvoie.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_A_LIBELLE_VOIE.libelle_voie IS 'Nom de voie.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_A_LIBELLE_VOIE.complement_nom_voie IS 'Complément de nom de voie.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_A_LIBELLE_VOIE.lateralite IS 'Latéralité de la voie : les deux côtés d''une voie physique peuvent appartenir à deux communes différentes.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_A_LIBELLE_VOIE.code_insee IS 'Code insee de la voie "administrative".';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_A_LIBELLE_VOIE.date_saisie IS 'Date de création du libellé de voie.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_A_LIBELLE_VOIE.date_modification IS 'Date de modification du libellé de voie.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_A_LIBELLE_VOIE.fid_pnom_saisie IS 'Clé étrangère vers la table TEMP_A_AGENT indiquant le pnom de l''agent créateur du libellé de voie.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_A_LIBELLE_VOIE.fid_pnom_modification IS 'Clé étrangère vers la table TEMP_A_AGENT indiquant le pnom de l''agent éditeur du libellé de voie.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_A_LIBELLE_VOIE.fid_voie IS 'Clé étrangère vers la table TEMP_A_VOIE permettant d''associer une voie physique à un nom de voie.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_A_LIBELLE_VOIE.fid_type_voie IS 'Clé étrangère vers la table TEMP_A_TYPE_VOIE permettant d''associer une voie à un type de voie.';

-- 3. Création de la clé primaire
ALTER TABLE G_BASE_VOIE.TEMP_A_LIBELLE_VOIE 
ADD CONSTRAINT TEMP_A_LIBELLE_VOIE_PK 
PRIMARY KEY("OBJECTID") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Création des clés étrangères
ALTER TABLE G_BASE_VOIE.TEMP_A_LIBELLE_VOIE
ADD CONSTRAINT TEMP_A_LIBELLE_VOIE_FID_VOIE_FK
FOREIGN KEY (fid_voie)
REFERENCES G_BASE_VOIE.TEMP_A_VOIE(objectid);

ALTER TABLE G_BASE_VOIE.TEMP_A_LIBELLE_VOIE
ADD CONSTRAINT TEMP_A_LIBELLE_VOIE_FID_TYPE_VOIE_FK
FOREIGN KEY (fid_type_voie)
REFERENCES G_BASE_VOIE.TEMP_A_TYPE_VOIE(objectid);

ALTER TABLE G_BASE_VOIE.TEMP_A_LIBELLE_VOIE
ADD CONSTRAINT TEMP_A_LIBELLE_VOIE_FID_PNOM_SAISIE_FK
FOREIGN KEY (fid_pnom_saisie)
REFERENCES G_BASE_VOIE.TEMP_A_AGENT(numero_agent);

ALTER TABLE G_BASE_VOIE.TEMP_A_LIBELLE_VOIE
ADD CONSTRAINT TEMP_A_LIBELLE_VOIE_FID_PNOM_MODIFICATION_FK
FOREIGN KEY (fid_pnom_modification)
REFERENCES G_BASE_VOIE.TEMP_A_AGENT(numero_agent);

-- 4. Création des index sur les clés étrangères et autres
CREATE INDEX TEMP_A_LIBELLE_VOIE_LIBELLE_VOIE_IDX ON G_BASE_VOIE.TEMP_A_LIBELLE_VOIE(libelle_voie)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TEMP_A_LIBELLE_VOIE_COMPLEMENT_NOM_VOIE_IDX ON G_BASE_VOIE.TEMP_A_LIBELLE_VOIE(complement_nom_voie)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TEMP_A_LIBELLE_VOIE_LATERALITE_IDX ON G_BASE_VOIE.TEMP_A_LIBELLE_VOIE(lateralite)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TEMP_A_LIBELLE_VOIE_CODE_INSEE_IDX ON G_BASE_VOIE.TEMP_A_LIBELLE_VOIE(code_insee)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TEMP_A_LIBELLE_VOIE_FID_PNOM_SAISIE_IDX ON G_BASE_VOIE.TEMP_A_LIBELLE_VOIE(fid_pnom_saisie)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TEMP_A_LIBELLE_VOIE_FID_PNOM_MODIFICATION_IDX ON G_BASE_VOIE.TEMP_A_LIBELLE_VOIE(fid_pnom_modification)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TEMP_A_LIBELLE_VOIE_FID_VOIE_IDX ON G_BASE_VOIE.TEMP_A_LIBELLE_VOIE(fid_voie)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TEMP_A_LIBELLE_VOIE_FID_TYPE_VOIE_IDX ON G_BASE_VOIE.TEMP_A_LIBELLE_VOIE(fid_type_voie)
    TABLESPACE G_ADT_INDX;

-- 5. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_BASE_VOIE.TEMP_A_LIBELLE_VOIE TO G_ADMIN_SIG;

/

