/*
La table TA_RUE regroupe toutes les informations des rues de la base voie.
*/

-- 1. Création de la table TA_RUE
CREATE TABLE G_BASE_VOIE.TA_RUE(
    objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
    libelle_rue VARCHAR2(100),
    nom VARCHAR2(100),
    code_insee CHAR(5),
    date_saisie DATE,
    fid_pnom_saisie NUMBER(38,0),
    date_modification DATE,
    fid_pnom_modification NUMBER(38,0)
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE G_BASE_VOIE.TA_RUE IS 'Table regroupant toutes les rues de la MEL. La rue est le composée de plusieurs voies elles-mêmes composées de plusieurs tronçons. Schématiquement la rue c''est le concept, la voie c''est l''objet et les tronçons composent l''objet. Ancienne table : TA_RUE';
COMMENT ON COLUMN G_BASE_VOIE.TA_RUE.objectid IS 'Clé primaire auto-incrémentée de la table.';
COMMENT ON COLUMN G_BASE_VOIE.TA_RUE.libelle_rue IS 'Libellé de la rue (imposé par la commune).';
COMMENT ON COLUMN G_BASE_VOIE.TA_RUE.nom IS 'Nom de la rue.';
COMMENT ON COLUMN G_BASE_VOIE.TA_RUE.code_insee IS 'Champ calculé via une requête spatiale, permettant d''associer à chaque rue le code insee de la commune dans laquelle elle se trouve (issue de la table G_REFERENTIEL.A_COMMUNES).';
COMMENT ON COLUMN G_BASE_VOIE.TA_RUE.date_saisie IS 'Date de saisie de la rue (via un trigger).';
COMMENT ON COLUMN G_BASE_VOIE.TA_RUE.fid_pnom_saisie IS 'Clé étrangère vers la table TA_AGENT permettant de récupérer le pnom de l''agent ayant créé une rue.';
COMMENT ON COLUMN G_BASE_VOIE.TA_RUE.date_modification IS 'Date de modification de la rue (via un trigger).';
COMMENT ON COLUMN G_BASE_VOIE.TA_RUE.fid_pnom_modification IS 'Clé étrangère vers la table TA_AGENT permettant de récupérer le pnom de l''agent ayant modifié une rue.';

-- 3. Création de la clé primaire
ALTER TABLE G_BASE_VOIE.TA_RUE 
ADD CONSTRAINT TA_RUE_PK 
PRIMARY KEY("OBJECTID") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Création des clés étrangères
ALTER TABLE G_BASE_VOIE.TA_RUE
ADD CONSTRAINT TA_RUE_FID_PNOM_SAISIE_FK 
FOREIGN KEY (fid_pnom_saisie)
REFERENCES G_BASE_VOIE.ta_agent(numero_agent);

ALTER TABLE G_BASE_VOIE.TA_RUE
ADD CONSTRAINT TA_RUE_FID_PNOM_MODIFICATION_FK
FOREIGN KEY (fid_pnom_modification)
REFERENCES G_BASE_VOIE.ta_agent(numero_agent);

-- 5. Création des index sur les clés étrangères
CREATE INDEX TA_RUE_FID_PNOM_SAISIE_IDX ON G_BASE_VOIE.TA_RUE(fid_pnom_saisie)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_RUE_FID_PNOM_MODIFICATION_IDX ON G_BASE_VOIE.TA_RUE(fid_pnom_modification)
    TABLESPACE G_ADT_INDX;

-- 6. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_BASE_VOIE.TA_RUE TO G_ADMIN_SIG;
