/*
Création de la table TA_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE - de la structure intermédiaire entre les tables sources et les vues matérialisées d''export du jeu de données - regroupant toutes les données des tronçons au format LITTERALIS (cf. les spécifications LITTERALIS), sauf la clé primaire.
*/
/*
DROP TABLE G_BASE_VOIE.TA_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE';
*/
-- 1. Création de la table
CREATE TABLE G_BASE_VOIE.TA_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE(
	Objectid NUMBER(38,0),
	NOM_VOIE VARCHAR2(4000 BYTE),
	CODE_INSEE VARCHAR2(5 BYTE),
	GEOM SDO_GEOMETRY
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE G_BASE_VOIE.TA_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE IS 'Table tampon du projet LITTERALIS - de la structure intermédiaire entre les tables sources et les vues matérialisées d''export du jeu de données - regroupant toutes les données des voies administratives (dont leur géométrie) au format LITTERALIS (cf. les spécifications LITTERALIS), sauf la clé primaire.';
COMMENT ON COLUMN G_BASE_VOIE.TA_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE.OBJECTID IS 'Clé primaire de la table correspondant aux identifiants des voies administratives de la table TA_VOIE_ADMINISTRATIVE.';
COMMENT ON COLUMN G_BASE_VOIE.TA_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE.NOM_VOIE IS 'Nom de la voie : type de voie + libelle_voie + complement_nom_voie.';
COMMENT ON COLUMN G_BASE_VOIE.TA_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE.CODE_INSEE IS 'Code INSEE de la voie principale présente dans TA_VOIE_ADMINISTRATIVE.';
COMMENT ON COLUMN G_BASE_VOIE.TA_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE.GEOM IS 'Géométrie de type multiligne des voies administratives.';

-- 3. Création de la clé primaire
ALTER TABLE G_BASE_VOIE.TA_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE
ADD CONSTRAINTS TA_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE_PK
PRIMARY KEY(OBJECTID)
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005)), 
    2154
);

-- 5. Création de l'index spatial sur le champ geom
CREATE INDEX TA_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE_SIDX
ON G_BASE_VOIE.TA_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
PARAMETERS('sdo_indx_dims=2, layer_gtype=MULTILINE, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');

-- 6. Création des index
CREATE INDEX TA_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE_CODE_INSEE_IDX
ON G_BASE_VOIE.TA_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE(CODE_INSEE)
TABLESPACE G_ADT_INDX;

CREATE INDEX TA_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE_NOM_VOIE_IDX
ON G_BASE_VOIE.TA_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE(NOM_VOIE)
TABLESPACE G_ADT_INDX;

-- 7. Affection des droits
GRANT SELECT ON G_BASE_VOIE.TA_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE TO G_ADMIN_SIG;

/

