/*
La table TEMP_A_VOIE regroupe tous les informations de chaque voie de la base voie.
*/

-- 1. Création de la table TEMP_A_VOIE
CREATE TABLE G_BASE_VOIE.TEMP_A_VOIE(
    objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE G_BASE_VOIE.TEMP_A_VOIE IS 'Table rassemblant les identifiant de toutes les voies PHYSIQUES (en opposition aux noms de voie : une voie physique peut avoir deux noms si elle appartient à deux communes différentes).';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_A_VOIE.objectid IS 'Clé primaire auto-incrémentée de la table (ses identifiants ne reprennent PAS ceux de VOIEVOI).';

-- 3. Création de la clé primaire
ALTER TABLE G_BASE_VOIE.TEMP_A_VOIE 
ADD CONSTRAINT TEMP_A_VOIE_PK 
PRIMARY KEY("OBJECTID") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 6. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_BASE_VOIE.TEMP_A_VOIE TO G_ADMIN_SIG;

/

