/*
Création de la table TEMP_TRONCON_CORRECT_LITTERALIS permettant d'avoir au format LITTERALIS les associations tronçon/voie où tout va bien.
*/

-- 1. Création de la table
CREATE TABLE G_BASE_VOIE.TEMP_TRONCON_CORRECT_LITTERALIS(
	CODE_TRONC VARCHAR2(254 BYTE),
    ID_TRONCON NUMBER(38,0),
	CLASSEMENT VARCHAR2(254 BYTE),
	CODE_RUE_G VARCHAR2(254 BYTE),
	NOM_RUE_G VARCHAR2(254 BYTE),
	INSEE_G VARCHAR2(254 BYTE),
	CODE_RUE_D VARCHAR2(254 BYTE),
	NOM_RUE_D VARCHAR2(254 BYTE),
	INSEE_D VARCHAR2(254 BYTE),
	LARGEUR NUMBER(8,0),
	GEOMETRY SDO_GEOMETRY
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE G_BASE_VOIE.TEMP_TRONCON_CORRECT_LITTERALIS IS 'Table contenant tous les tronçons disposant d''une seule domanialité et affecté à une seule voie.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_TRONCON_CORRECT_LITTERALIS.CODE_TRONC IS 'Identifiant du tronçon au format LITTERALIS (VARCHAR).';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_TRONCON_CORRECT_LITTERALIS.ID_TRONCON IS 'Identifiant du tronçon au format base voie (NUMBER).';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_TRONCON_CORRECT_LITTERALIS.CLASSEMENT IS 'Domanialité de chaque voie au format LITTERALIS.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_TRONCON_CORRECT_LITTERALIS.CODE_RUE_G IS 'Identifiant de chaque voie de gauche du tronçon au format LITTERALIS (VARCHAR).';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_TRONCON_CORRECT_LITTERALIS.NOM_RUE_G IS 'Libelle voie + complément nom voie issus de TA_VOIE pour la voie de gauche du tronçon .';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_TRONCON_CORRECT_LITTERALIS.INSEE_G IS 'Code INSEE de la commune d''appartenance de la voie de gauche du tronçon au format LITTERALIS (VARCHAR).';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_TRONCON_CORRECT_LITTERALIS.CODE_RUE_D IS 'Identifiant de chaque voie de droite du tronçon au format LITTERALIS (VARCHAR).';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_TRONCON_CORRECT_LITTERALIS.NOM_RUE_D IS 'Libelle voie + complément nom voie issus de TA_VOIE pour la voie de droite du tronçon .';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_TRONCON_CORRECT_LITTERALIS.INSEE_D IS 'Code INSEE de la commune d''appartenance de la voie de droite du tronçon au format LITTERALIS (VARCHAR).';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_TRONCON_CORRECT_LITTERALIS.LARGEUR IS 'Largeur de la voie de type NUMBER, c-à-d NULL pour nous.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_TRONCON_CORRECT_LITTERALIS.GEOMETRY IS 'Géométrie de chaque tronçon de type multiligne.';

-- 3. Création de la clé primaire
ALTER TABLE G_BASE_VOIE.TEMP_TRONCON_CORRECT_LITTERALIS
ADD CONSTRAINTS TEMP_TRONCON_CORRECT_LITTERALIS_PK
PRIMARY KEY(CODE_TRONC)
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TEMP_TRONCON_CORRECT_LITTERALIS',
    'GEOMETRY',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005)), 
    2154
);
COMMIT;

-- 5. Création des index
CREATE INDEX TEMP_TRONCON_CORRECT_LITTERALIS_SIDX
ON G_BASE_VOIE.TEMP_TRONCON_CORRECT_LITTERALIS(GEOMETRY)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2, layer_gtype=MULTILINE, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');

CREATE INDEX TEMP_TRONCON_CORRECT_LITTERALIS_ID_TRONCON_IDX
ON G_BASE_VOIE.TEMP_TRONCON_CORRECT_LITTERALIS(ID_TRONCON)
TABLESPACE G_ADT_INDX;

-- 6. Affection des droits
GRANT SELECT ON G_BASE_VOIE.TEMP_TRONCON_CORRECT_LITTERALIS TO G_ADMIN_SIG;

/

