/*
La table TA_POINT_INTERET regroupe tous les point d''intérêts de la base voie.
*/

-- 1. Création de la table TA_POINT_INTERET
CREATE TABLE G_BASE_VOIE.TA_POINT_INTERET(
    objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
    geom SDO_GEOMETRY,
    nom VARCHAR2(200),
    complement_infos VARCHAR2(250),
    code_insee VARCHAR2(4000 BYTE) GENERATED ALWAYS AS (GET_CODE_INSEE_CONTENU(geom)) VIRTUAL, 
    date_saisie DATE DEFAULT sysdate NOT NULL,
    date_modification DATE DEFAULT sysdate NOT NULL,
    fid_libelle NUMBER(38,0),
    fid_pnom_saisie NUMBER(38,0) NOT NULL,
    fid_pnom_modification NUMBER(38,0) NOT NULL
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE G_BASE_VOIE.TA_POINT_INTERET IS 'Table regroupant les points d''intérêt de type mairie ou mairie de quartier. Ancienne table : ILTALPU.';
COMMENT ON COLUMN G_BASE_VOIE.TA_POINT_INTERET.objectid IS 'Clé primaire auto-incrémentée de la table identifiant chaque point d''intérêt. Cette pk remplace l''ancien identifiant cnumlpu.';
COMMENT ON COLUMN G_BASE_VOIE.TA_POINT_INTERET.geom IS 'Géométrie de type point de chaque point d''intérêt présent dans la table.';
COMMENT ON COLUMN G_BASE_VOIE.TA_POINT_INTERET.nom IS 'Nom du Point d''intérêt correspondant au champ CLIBLPU de l''ancienne table ILTALPU.';
COMMENT ON COLUMN G_BASE_VOIE.TA_POINT_INTERET.complement_infos IS 'Complément d''informations du point d''intérêt.';
COMMENT ON COLUMN G_BASE_VOIE.TA_POINT_INTERET.code_insee IS 'Champ calculé via une requête spatiale, permettant d''associer à chaque point d''intérêt le code insee de la commune dans laquelle il se trouve (issue de la table G_REFERENTIEL.MEL_COMMUNE).';
COMMENT ON COLUMN G_BASE_VOIE.TA_POINT_INTERET.date_saisie IS 'Date de saisie du point d''intérêt (par défaut il s''agit de la date du jour).';
COMMENT ON COLUMN G_BASE_VOIE.TA_POINT_INTERET.date_modification IS 'Dernière date de modification du point d''intérêt (par défaut il s''agit de la date du jour).';
COMMENT ON COLUMN G_BASE_VOIE.TA_POINT_INTERET.fid_pnom_saisie IS 'Clé étrangère vers la table TA_AGENT permettant de récupérer le pnom de l''agent ayant créé un point d''intérêt.';
COMMENT ON COLUMN G_BASE_VOIE.TA_POINT_INTERET.fid_pnom_modification IS 'Clé étrangère vers la table TA_AGENT permettant de récupérer le pnom de l''agent ayant modifié un point d''intérêt.';

-- 3. Création de la clé primaire
ALTER TABLE G_BASE_VOIE.TA_POINT_INTERET 
ADD CONSTRAINT TA_POINT_INTERET_PK 
PRIMARY KEY("OBJECTID") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TA_POINT_INTERET',
    'geom',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005)), 
    2154
);

-- 5. Création de l'index spatial sur le champ geom
CREATE INDEX TA_POINT_INTERET_SIDX
ON G_BASE_VOIE.TA_POINT_INTERET(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2, layer_gtype=POINT, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');

-- 6. Création des clés étrangères
ALTER TABLE G_BASE_VOIE.TA_POINT_INTERET
ADD CONSTRAINT TA_POINT_INTERET_FID_PNOM_SAISIE_FK
FOREIGN KEY (fid_pnom_saisie)
REFERENCES G_BASE_VOIE.TA_AGENT(numero_agent);

ALTER TABLE G_BASE_VOIE.TA_POINT_INTERET
ADD CONSTRAINT TA_POINT_INTERET_FID_PNOM_MODIFICATION_FK
FOREIGN KEY (fid_pnom_modification)
REFERENCES G_BASE_VOIE.TA_AGENT(numero_agent);

ALTER TABLE G_BASE_VOIE.TA_POINT_INTERET
ADD CONSTRAINT TA_POINT_INTERET_FID_LIBELLE_FK
FOREIGN KEY (fid_libelle)
REFERENCES G_BASE_VOIE.TA_LIBELLE(objectid);

-- 7. Création des index sur les clés étrangères
CREATE INDEX TA_POINT_INTERET_FID_PNOM_SAISIE_IDX ON G_BASE_VOIE.TA_POINT_INTERET(fid_pnom_saisie)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_POINT_INTERET_FID_PNOM_MODIFICATION_IDX ON G_BASE_VOIE.TA_POINT_INTERET(fid_pnom_modification)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_POINT_INTERET_FID_LIBELLE_IDX ON G_BASE_VOIE.TA_POINT_INTERET(fid_libelle)
    TABLESPACE G_ADT_INDX;

-- 8. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_BASE_VOIE.TA_POINT_INTERET TO G_ADMIN_SIG;
