/*
Table - du projet C de correction des latéralités des voies en limites de commune - contenant les centroïdes des voies administratives de type simple (2002). Aucune multiligne n''est présente dans la table.
*/
CREATE TABLE G_BASE_VOIE.TEMP_C_CENTROIDE_VOIE_ADMINISTRATIVE_MULTILIGNE(
    objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
    id_voie_administrative NUMBER(38,0),
    code_insee VARCHAR2(5 BYTE),
    geom SDO_GEOMETRY
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE G_BASE_VOIE.TEMP_C_CENTROIDE_VOIE_ADMINISTRATIVE_MULTILIGNE IS 'Table contenant les centroïdes des voies administratives de type multiligne (2006). Aucune ligne simple n''est présente dans la table.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_C_CENTROIDE_VOIE_ADMINISTRATIVE_MULTILIGNE.objectid IS 'Clé primaire auto-incrémentée de la table.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_C_CENTROIDE_VOIE_ADMINISTRATIVE_MULTILIGNE.geom IS 'Géométrie de type point de chaque centroïde présent dans la table.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_C_CENTROIDE_VOIE_ADMINISTRATIVE_MULTILIGNE.id_voie_administrative IS 'Identifiant de la voie administrative.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_C_CENTROIDE_VOIE_ADMINISTRATIVE_MULTILIGNE.code_insee IS 'Code INSEE de chaque voie administrative.';

-- 3. Création de la clé primaire
ALTER TABLE G_BASE_VOIE.TEMP_C_CENTROIDE_VOIE_ADMINISTRATIVE_MULTILIGNE 
ADD CONSTRAINT TEMP_C_CENTROIDE_VOIE_ADMINISTRATIVE_MULTILIGNE_PK 
PRIMARY KEY("OBJECTID") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TEMP_C_CENTROIDE_VOIE_ADMINISTRATIVE_MULTILIGNE',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005)), 
    2154
);
COMMIT;

-- 5. Création de l'index spatial sur le champ geom
CREATE INDEX TEMP_C_CENTROIDE_VOIE_ADMINISTRATIVE_MULTILIGNE_SIDX
ON G_BASE_VOIE.TEMP_C_CENTROIDE_VOIE_ADMINISTRATIVE_MULTILIGNE(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
PARAMETERS('sdo_indx_dims=2, layer_gtype=MULTILIGNE, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');

-- 7. Création des index sur les clés étrangères et autres
CREATE INDEX TEMP_C_CENTROIDE_VOIE_ADMINISTRATIVE_MULTILIGNE_ID_VOIE_ADMINISTRATIVE_IDX ON G_BASE_VOIE.TEMP_C_CENTROIDE_VOIE_ADMINISTRATIVE_MULTILIGNE(id_voie_administrative)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TEMP_C_CENTROIDE_VOIE_ADMINISTRATIVE_MULTILIGNE_CODE_INSEE_IDX ON G_BASE_VOIE.TEMP_C_CENTROIDE_VOIE_ADMINISTRATIVE_MULTILIGNE(code_insee)
    TABLESPACE G_ADT_INDX;

-- 8. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_BASE_VOIE.TEMP_C_CENTROIDE_VOIE_ADMINISTRATIVE_MULTILIGNE TO G_ADMIN_SIG;

/

