/*
La table TEMP_C_RELATION_TRONCON_VOIE_PHYSIQUE - du projet C de correction de la latéralité des voies - permet d''associer les tronçons de la table TEMP_C_TRONCON à leur voie présente dans TEMP_C_VOIE_PHYSIQUE. 
Il s''agit ici d''une table temporaire qui sert à faire la transition vers une relation tronçon 1.1 / 1.n voie physique.
*/

-- 1. Création de la table TEMP_C_RELATION_TRONCON_VOIE_PHYSIQUE
CREATE TABLE G_BASE_VOIE.TEMP_C_RELATION_TRONCON_VOIE_PHYSIQUE(
    objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
    sens CHAR(1) NULL,
    fid_voie_physique NUMBER(38,0) NOT NULL,
    fid_troncon NUMBER(38,0) NOT NULL
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE G_BASE_VOIE.TEMP_C_RELATION_TRONCON_VOIE_PHYSIQUE IS 'Table pivot - du projet C de correction de la latéralité des voies - permettant d''associer les tronçons de la table TEMP_C_TRONCON à leur voie présente dans TEMP_C_VOIE_PHYSIQUE. Il s''agit ici d''une table temporaire qui sert à faire la transition vers une relation tronçon 1.1 / 1.n voie physique.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_C_RELATION_TRONCON_VOIE_PHYSIQUE.objectid IS 'Clé primaire auto-incrémentée de la table.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_C_RELATION_TRONCON_VOIE_PHYSIQUE.sens IS 'Code permettant de connaître le sens de saisie du tronçon par rapport au sens de la voie.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_C_RELATION_TRONCON_VOIE_PHYSIQUE.fid_voie_physique IS 'Clé étrangère vers la table TEMP_C_VOIE_PHYSIQUE permettant d''associer une voie à un ou plusieurs tronçons. Ancien champ : CCOMVOI.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_C_RELATION_TRONCON_VOIE_PHYSIQUE.fid_troncon IS 'Clé étrangère vers la table TEMP_C_TRONCON permettant d''associer un ou plusieurs tronçons à une voie. Ancien champ : CNUMTRC.';

-- 3. Création de la clé primaire
ALTER TABLE G_BASE_VOIE.TEMP_C_RELATION_TRONCON_VOIE_PHYSIQUE 
ADD CONSTRAINT TEMP_C_RELATION_TRONCON_VOIE_PHYSIQUE_PK 
PRIMARY KEY("OBJECTID") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Création des clés étrangères
ALTER TABLE G_BASE_VOIE.TEMP_C_RELATION_TRONCON_VOIE_PHYSIQUE
ADD CONSTRAINT TEMP_C_RELATION_TRONCON_VOIE_PHYSIQUE_FID_VOIE_PHYSIQUE_FK
FOREIGN KEY (fid_voie_physique)
REFERENCES G_BASE_VOIE.TEMP_C_VOIE_PHYSIQUE(objectid);

ALTER TABLE G_BASE_VOIE.TEMP_C_RELATION_TRONCON_VOIE_PHYSIQUE
ADD CONSTRAINT TEMP_C_RELATION_TRONCON_VOIE_PHYSIQUE_FID_TRONCON_FK
FOREIGN KEY (fid_troncon)
REFERENCES G_BASE_VOIE.TEMP_C_TRONCON(objectid);

-- 5. Création des index sur les clés étrangères
CREATE INDEX TEMP_C_RELATION_TRONCON_VOIE_PHYSIQUE_FID_VOIE_PHYSIQUE_IDX ON G_BASE_VOIE.TEMP_C_RELATION_TRONCON_VOIE_PHYSIQUE(fid_voie_physique)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TEMP_C_RELATION_TRONCON_VOIE_PHYSIQUE_FID_TRONCON_IDX ON G_BASE_VOIE.TEMP_C_RELATION_TRONCON_VOIE_PHYSIQUE(fid_troncon)
    TABLESPACE G_ADT_INDX;

-- 6. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_BASE_VOIE.TEMP_C_RELATION_TRONCON_VOIE_PHYSIQUE TO G_ADMIN_SIG;

/

