/*
La table TEMP_C_BUFFER_LIMITE_COMMUNALE - du projet C de correction de la latéralité des voies - contenant les buffers des centroïdes des voies en limite de commune dont il faut déterminer la latéralité.
*/

DROP TABLE TEMP_C_BUFFER_LIMITE_COMMUNALE CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TEMP_C_BUFFER_LIMITE_COMMUNALE';
COMMIT;

-- 1. Création de la table TEMP_C_BUFFER_LIMITE_COMMUNALE
CREATE TABLE G_BASE_VOIE.TEMP_C_BUFFER_LIMITE_COMMUNALE(
    OBJECTID NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
    CODE_INSEE VARCHAR2(5 BYTE),
    GEOM SDO_GEOMETRY
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE G_BASE_VOIE.TEMP_C_BUFFER_LIMITE_COMMUNALE IS 'Table - du projet C de correction de la latéralité des voies - contenant les buffers des limites communales. Cette est créée dans le cadre de l''identification des latéralités des voies.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_C_BUFFER_LIMITE_COMMUNALE.objectid IS 'Clé primaire de la table correspondant aux identifiants de la table TEMP_C_LIMITE_COMMUNALE.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_C_BUFFER_LIMITE_COMMUNALE.code_insee IS 'Code INSEE de la commune.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_C_BUFFER_LIMITE_COMMUNALE.geom IS 'Géométrie de type multipolygone.';

-- 3. Création de la clé primaire
ALTER TABLE G_BASE_VOIE.TEMP_C_BUFFER_LIMITE_COMMUNALE 
ADD CONSTRAINT TEMP_C_BUFFER_LIMITE_COMMUNALE_PK 
PRIMARY KEY("OBJECTID") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TEMP_C_BUFFER_LIMITE_COMMUNALE',
    'GEOM',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005)), 
    2154
);

-- 5. Création de l'index spatial sur le champ geom
CREATE INDEX TEMP_C_BUFFER_LIMITE_COMMUNALE_SIDX
ON G_BASE_VOIE.TEMP_C_BUFFER_LIMITE_COMMUNALE(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2, layer_gtype=MULTIPOLYGON, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');

-- 7. Création des index sur les clés étrangères et autres
CREATE INDEX TEMP_C_BUFFER_LIMITE_COMMUNALE_CODE_INSEE_VOIE_IDX ON G_BASE_VOIE.TEMP_C_BUFFER_LIMITE_COMMUNALE(code_insee)
    TABLESPACE G_ADT_INDX;

-- 8. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_BASE_VOIE.TEMP_C_BUFFER_LIMITE_COMMUNALE TO G_ADMIN_SIG;

/

