/*
La table TEMP_CORRECTION_PROJET_A_VOIE regroupe tous les informations de chaque voie de la base voie.
*/

-- 1. Création de la table TEMP_CORRECTION_PROJET_A_VOIE
CREATE TABLE G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_VOIE(
    objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
    libelle_voie VARCHAR2(50) NULL,
    complement_nom_voie VARCHAR2(50),
    cnumcom NUMBER(3,0),
    ccodrvo VARCHAR2(4 BYTE),
    cdvalvoi VARCHAR2(1 BYTE),
    date_saisie DATE DEFAULT sysdate NULL,
    date_modification DATE DEFAULT sysdate NULL,
    fid_pnom_saisie NUMBER(38,0) NULL,
    fid_pnom_modification NUMBER(38,0) NULL,
    fid_typevoie NUMBER(38,0) NULL,
    genre VARCHAR2(3 BYTE) NULL,
    fid_rivoli NUMBER(38,0) NULL
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_VOIE IS 'Table transitoire permettant les corrections pour ensuite intégrer les données dans les tables de production. Elle rassemblent toutes les informations pour chaque voie de la base. Ancienne table : VOIEVOI';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_VOIE.objectid IS 'Clé primaire auto-incrémentée de la table. Elle remplace l''ancien identifiant ccomvoie.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_VOIE.libelle_voie IS 'Nom de la voie.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_VOIE.complement_nom_voie IS 'Complément du nom de la voie.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_VOIE.cnumcom IS 'Code commune (différent du code INSEE) de la voie rempli à la main.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_VOIE.ccodrvo IS 'Code RIVOLI de la voie (différent du code fantoir).';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_VOIE.cdvalvoi IS 'Champ permettant de distinguer les voies valides des voies invalides.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_VOIE.date_saisie IS 'Date de saisie de la voie (par défaut la date du jour).';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_VOIE.date_modification IS 'Date de modification de la voie (par défaut la date du jour).';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_VOIE.fid_pnom_saisie IS 'Clé étrangère vers la table TA_AGENT permettant de récupérer le pnom de l''agent ayant créé une voie.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_VOIE.fid_pnom_modification IS 'Clé étrangère vers la table TA_AGENT permettant de récupérer le pnom de l''agent ayant modifié une voie.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_VOIE.fid_typevoie IS 'Clé étangère vers la table TA_TYPE_VOIE permettant de catégoriser les voies de la base.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_VOIE.genre IS 'Genre du nom de la voie : masculin, féminin, neutre et non-identifié.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_VOIE.fid_rivoli IS 'Clé étrangère vers la table TA_RIVOLI permettant d''associer un code RIVOLI à chaque voie.';

-- 3. Création de la clé primaire
ALTER TABLE G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_VOIE 
ADD CONSTRAINT TEMP_CORRECTION_PROJET_A_VOIE_PK 
PRIMARY KEY("OBJECTID") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 5. Création des index
CREATE INDEX TEMP_CORRECTION_PROJET_A_VOIE_FID_PNOM_SAISIE_IDX ON G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_VOIE(fid_pnom_saisie)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TEMP_CORRECTION_PROJET_A_VOIE_FID_PNOM_MODIFICATION_IDX ON G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_VOIE(fid_pnom_modification)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TEMP_CORRECTION_PROJET_A_VOIE_FID_TYPEVOIE_IDX ON G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_VOIE(fid_typevoie)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TEMP_CORRECTION_PROJET_A_VOIE_GENRE_IDX ON G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_VOIE(genre)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TEMP_CORRECTION_PROJET_A_VOIE_FID_RIVOLI_IDX ON G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_VOIE(fid_rivoli)
    TABLESPACE G_ADT_INDX;
    
CREATE INDEX TEMP_CORRECTION_PROJET_A_VOIE_CNUMCOM_IDX ON G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_VOIE(cnumcom)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TEMP_CORRECTION_PROJET_A_VOIE_CCODRVO_IDX ON G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_VOIE(ccodrvo)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TEMP_CORRECTION_PROJET_A_VOIE_CDVALVOI_IDX ON G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_VOIE(cdvalvoi)
    TABLESPACE G_ADT_INDX;

-- 6. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_BASE_VOIE.TEMP_CORRECTION_PROJET_A_VOIE TO G_ADMIN_SIG;

/

