/*
La table TA_FAMILLE regroupe toutes les familles des types détats et d''objets de la base base voie.
*/

-- 1. Création de la table TA_FAMILLE
CREATE TABLE G_BASE_VOIE.TA_FAMILLE(
    objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
    valeur VARCHAR2(400) NOT NULL
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE G_BASE_VOIE.TA_FAMILLE IS 'Table listant toutes les familles des types d''états et d''objets de la base base voie, ce qui permet de les catégoriser.';
COMMENT ON COLUMN G_BASE_VOIE.TA_FAMILLE.objectid IS 'Clé primaire auto-incrémentée de la table.';
COMMENT ON COLUMN G_BASE_VOIE.TA_FAMILLE.valeur IS 'Famille d''objets ou d''actions permettant de catégoriser un état ou un objet dans la base voie.';

-- 3. Création de la clé primaire
ALTER TABLE G_BASE_VOIE.TA_FAMILLE 
ADD CONSTRAINT TA_FAMILLE_PK 
PRIMARY KEY("OBJECTID") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_BASE_VOIE.TA_FAMILLE TO G_ADMIN_SIG;