/*
La table TA_RUE_LOG regroupe toutes les évolutions des informations des rues de TA_RUE.
*/

-- 1. Création de la table TA_RUE_LOG
CREATE TABLE G_BASE_VOIE.TA_RUE_LOG(
    objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
    fid_rue NUMBER(38,0) NOT NULL,
    libelle_rue VARCHAR2(100) NOT NULL,
    nom VARCHAR2(100) NOT NULL,
    code_insee CHAR(5) NOT NULL,
    fid_type_action NUMBER(38,0) NOT NULL,
    date_action DATE NOT NULL,
    fid_pnom NUMBER(38,0) NOT NULL
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE G_BASE_VOIE.TA_RUE_LOG IS '';
COMMENT ON COLUMN G_BASE_VOIE.TA_RUE_LOG.objectid IS 'Clé primaire auto-incrémentée de la table.';
COMMENT ON COLUMN G_BASE_VOIE.TA_RUE_LOG.fid_rue IS 'Clé étrangère vers la table TA_RUE permettant de savoirsur quelle rue ont été faites les actions.';
COMMENT ON COLUMN G_BASE_VOIE.TA_RUE_LOG.libelle_rue IS 'Libellé de la rue (imposé par la commune).';
COMMENT ON COLUMN G_BASE_VOIE.TA_RUE_LOG.nom IS 'Nom de la rue.';
COMMENT ON COLUMN G_BASE_VOIE.TA_RUE_LOG.code_insee IS 'Champ calculé via une requête spatiale, permettant d''associer à chaque rue le code insee de la commune dans laquelle elle se trouve (issue de la table G_REFERENTIEL.A_COMMUNES).';
COMMENT ON COLUMN G_BASE_VOIE.TA_RUE_LOG.fid_type_action IS 'Clé étrangère vers la table TA_LIBELLE, permettant d''associer un type d''action à une voie.';
COMMENT ON COLUMN G_BASE_VOIE.TA_RUE_LOG.date_action IS 'Date de saisie, modification ou suppression de la rue.';
COMMENT ON COLUMN G_BASE_VOIE.TA_RUE_LOG.fid_pnom IS 'Clé étrangère vers la table TA_AGENT permettant d''associer le pnom d''un agent à la voie qu''il a créé, modifié ou supprimé.';

-- 3. Création de la clé primaire
ALTER TABLE G_BASE_VOIE.TA_RUE_LOG 
ADD CONSTRAINT TA_RUE_LOG_PK 
PRIMARY KEY("OBJECTID") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Création des clés étrangères
ALTER TABLE G_BASE_VOIE.TA_RUE_LOG
ADD CONSTRAINT TA_RUE_LOG_FID_TYPE_ACTION_FK 
FOREIGN KEY (fid_type_action)
REFERENCES G_BASE_VOIE.ta_libelle(objectid);

ALTER TABLE G_BASE_VOIE.TA_RUE_LOG
ADD CONSTRAINT TA_RUE_LOG_FID_PNOM_FK
FOREIGN KEY (fid_pnom)
REFERENCES G_BASE_VOIE.ta_agent(numero_agent);

-- 5. Création des index sur les clés étrangères
CREATE INDEX TA_RUE_LOG_FID_TYPE_ACTION_IDX ON G_BASE_VOIE.TA_RUE_LOG(fid_type_action)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_RUE_LOG_FID_PNOM_IDX ON G_BASE_VOIE.TA_RUE_LOG(fid_pnom)
    TABLESPACE G_ADT_INDX;

-- 6. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_BASE_VOIE.TA_RUE_LOG TO G_ADMIN_SIG;
