-- 1. Création de la table
CREATE TABLE G_BASE_VOIE.TEMP_C_TRANSIT_TRONCON_VOIE_PHYSIQUE(
	id_troncon NUMBER(38,0),
	old_id_voie_physique NUMBER(38,0),
	new_id_voie_physique NUMBER(38,0)
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE G_BASE_VOIE.TEMP_C_TRANSIT_TRONCON_VOIE_PHYSIQUE IS 'Table - du projet C de correction de la latéralité des voies - rassemblant tous les tronçons affectés à plusieurs voies physiques.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_C_TRANSIT_TRONCON_VOIE_PHYSIQUE.id_troncon IS 'Identifiant des tronçons.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_C_TRANSIT_TRONCON_VOIE_PHYSIQUE.old_id_voie_physique IS 'Ancien identifiant de voie physique.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_C_TRANSIT_TRONCON_VOIE_PHYSIQUE.new_id_voie_physique IS 'Nouvel identifiant de voie physique.';

-- 3. Création de la clé primaire
ALTER TABLE G_BASE_VOIE.TEMP_C_TRANSIT_TRONCON_VOIE_PHYSIQUE 
ADD CONSTRAINT TEMP_C_TRANSIT_TRONCON_VOIE_PHYSIQUE_PK 
PRIMARY KEY("ID_TRONCON") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 5. Création des index
CREATE INDEX TEMP_C_TRANSIT_TRONCON_VOIE_PHYSIQUE_OLD_ID_VOIE_PHYSIQUE_IDX ON G_BASE_VOIE.TEMP_C_TRANSIT_TRONCON_VOIE_PHYSIQUE(OLD_ID_VOIE_PHYSIQUE)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TEMP_C_TRANSIT_TRONCON_VOIE_PHYSIQUE_NEW_ID_VOIE_PHYSIQUE_IDX ON G_BASE_VOIE.TEMP_C_TRANSIT_TRONCON_VOIE_PHYSIQUE(NEW_ID_VOIE_PHYSIQUE)
    TABLESPACE G_ADT_INDX;

-- 6. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_BASE_VOIE.TEMP_C_TRANSIT_TRONCON_VOIE_PHYSIQUE TO G_ADMIN_SIG;

/


