/*
La table TA_RELATION_VOIE_ADMINISTRATIVE_SUPRA_COMMUNALE faisant le lien entre la table des voies administratives (TA_VOIE_ADMINISTRATIVE) et celle des voies supra-communales de la DEPV (OUT_DOMANIALITE).
*/
/*
DROP TABLE G_BASE_VOIE.TA_RELATION_VOIE_ADMINISTRATIVE_SUPRA_COMMUNALE CASCADE CONSTRAINTS;
*/
-- 1. Création de la table TA_RELATION_VOIE_ADMINISTRATIVE_SUPRA_COMMUNALE
CREATE TABLE G_BASE_VOIE.TA_RELATION_VOIE_ADMINISTRATIVE_SUPRA_COMMUNALE(
    fid_voie_administrative NUMBER(38,0),
    fid_voie_supra_communale NUMBER(38,0)
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE G_BASE_VOIE.TA_RELATION_VOIE_ADMINISTRATIVE_SUPRA_COMMUNALE IS 'Table de relation entre la table des voies administratives (TA_VOIE_ADMINISTRATIVE) et celle des voies supra-communales de la DEPV (EXRD_IDSUPVOIE).';
COMMENT ON COLUMN G_BASE_VOIE.TA_RELATION_VOIE_ADMINISTRATIVE_SUPRA_COMMUNALE.fid_voie_administrative IS 'Clé primaire et étrangère de la table permettant d''associer une voie administrative à une voie supra-communale.';
COMMENT ON COLUMN G_BASE_VOIE.TA_RELATION_VOIE_ADMINISTRATIVE_SUPRA_COMMUNALE.fid_voie_supra_communale IS 'Clé primaire et étrangère de la table permettant d''associer une voie supra-communale à une voie administrative.';

-- 3. Création de la clé primaire
ALTER TABLE G_BASE_VOIE.TA_RELATION_VOIE_ADMINISTRATIVE_SUPRA_COMMUNALE 
ADD CONSTRAINT TA_RELATION_VOIE_ADMINISTRATIVE_SUPRA_COMMUNALE_PK 
PRIMARY KEY("FID_VOIE_ADMINISTRATIVE", "FID_VOIE_SUPRA_COMMUNALE") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Création des clés étrangères
ALTER TABLE G_BASE_VOIE.TA_RELATION_VOIE_ADMINISTRATIVE_SUPRA_COMMUNALE
ADD CONSTRAINT TA_RELATION_VOIE_ADMINISTRATIVE_SUPRA_COMMUNALE_FID_VOIE_ADMINISTRATIVE_FK 
FOREIGN KEY (fid_voie_administrative)
REFERENCES G_BASE_VOIE.TA_VOIE_ADMINISTRATIVE(objectid);

ALTER TABLE G_BASE_VOIE.TA_RELATION_VOIE_ADMINISTRATIVE_SUPRA_COMMUNALE
ADD CONSTRAINT TA_RELATION_VOIE_ADMINISTRATIVE_SUPRA_COMMUNALE_FID_VOIE_SUPRA_COMMUNALE_FK
FOREIGN KEY (fid_voie_supra_communale)
REFERENCES G_BASE_VOIE.TA_VOIE_SUPRA_COMMUNALE(objectid);

-- 7. Création des index sur les clés étrangères et autres
CREATE INDEX TA_RELATION_VOIE_ADMINISTRATIVE_SUPRA_COMMUNALE_FID_VOIE_ADMINISTRATIVE_IDX ON G_BASE_VOIE.TA_RELATION_VOIE_ADMINISTRATIVE_SUPRA_COMMUNALE(fid_voie_administrative)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_RELATION_VOIE_ADMINISTRATIVE_SUPRA_COMMUNALE_FID_VOIE_SUPRA_COMMUNALE_IDX ON G_BASE_VOIE.TA_RELATION_VOIE_ADMINISTRATIVE_SUPRA_COMMUNALE(fid_voie_supra_communale)
    TABLESPACE G_ADT_INDX;

-- 8. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_BASE_VOIE.TA_RELATION_VOIE_ADMINISTRATIVE_SUPRA_COMMUNALE TO G_ADMIN_SIG;

/

