/*
La table TEMP_RELATION_TRONCON_VOIE regroupant tous les types et états permettant de catégoriser les objets de la base voie.
*/

-- 1. Création de la table TEMP_RELATION_TRONCON_VOIE
CREATE TABLE G_BASE_VOIE.TEMP_RELATION_TRONCON_VOIE(
    objectid NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
    sens CHAR(1) NULL,
    cvalide VARCHAR2(1 BYTE),
    fid_voie NUMBER(38,0) NULL,
    fid_troncon NUMBER(38,0) NULL,
    date_saisie DATE DEFAULT sysdate NULL,
    date_modification DATE DEFAULT sysdate NULL,
    fid_pnom_saisie NUMBER(38,0) NULL,
    fid_pnom_modification NUMBER(38,0) NULL
);

-- 2. Création des commentaires sur la table et les champs
COMMENT ON TABLE G_BASE_VOIE.TEMP_RELATION_TRONCON_VOIE IS 'Table pivot transitoire permettant les corrections pour ensuite intégrer les données dans les tables de production. Elle permet d''associer les tronçons de la table temp_troncon à leur voie présente dans temp_voie. Ancienne table : VOIECVT.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_RELATION_TRONCON_VOIE.objectid IS 'Clé primaire auto-incrémentée de la table.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_RELATION_TRONCON_VOIE.sens IS 'Code permettant de connaître le sens du tronçon. Ancien champ : CCODSTR. A préciser avec Marie-Hélène, car les valeurs ne sont pas compréhensibles sans documentation.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_RELATION_TRONCON_VOIE.cvalide IS 'Champ permettant d''identifier les relations tronçon/voie valides ou invalides.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_RELATION_TRONCON_VOIE.fid_voie IS 'Clé étrangère vers la table temp_voie permettant d''associer une voie à un ou plusieurs tronçons. Ancien champ : CCOMVOI.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_RELATION_TRONCON_VOIE.fid_troncon IS 'Clé étrangère vers la table temp_troncon permettant d''associer un ou plusieurs tronçons à une voie. Ancien champ : CNUMTRC.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_RELATION_TRONCON_VOIE.date_saisie IS 'Date de saisie de la relation troncon/voie en base (par défaut la date du jour).';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_RELATION_TRONCON_VOIE.date_modification IS 'Date de la dernière modification de la relation troncon/voie en base (par défaut la date du jour).';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_RELATION_TRONCON_VOIE.fid_pnom_saisie IS 'Clé étrangère vers la table TA_AGENT permettant de récupérer le pnom de l''agent ayant créé la relation.';
COMMENT ON COLUMN G_BASE_VOIE.TEMP_RELATION_TRONCON_VOIE.fid_pnom_modification IS 'Clé étrangère vers la table TA_AGENT permettant de récupérer le pnom de l''agent ayant modifié la relation.';

-- 3. Création de la clé primaire
ALTER TABLE G_BASE_VOIE.TEMP_RELATION_TRONCON_VOIE 
ADD CONSTRAINT TEMP_RELATION_TRONCON_VOIE_PK 
PRIMARY KEY("OBJECTID") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 5. Création des index sur les clés étrangères
CREATE INDEX TEMP_RELATION_TRONCON_VOIE_FID_VOIE_IDX ON G_BASE_VOIE.TEMP_RELATION_TRONCON_VOIE(fid_voie)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TEMP_RELATION_TRONCON_VOIE_FID_TRONCON_IDX ON G_BASE_VOIE.TEMP_RELATION_TRONCON_VOIE(fid_troncon)
    TABLESPACE G_ADT_INDX;

CREATE INDEX TEMP_RELATION_TRONCON_VOIE_CVALIDE_IDX ON G_BASE_VOIE.TEMP_RELATION_TRONCON_VOIE(cvalide)
    TABLESPACE G_ADT_INDX;

-- 6. Affectation du droit de sélection sur les objets de la table aux administrateurs
GRANT SELECT ON G_BASE_VOIE.TEMP_RELATION_TRONCON_VOIE TO G_ADMIN_SIG;

/

