/*
Requêtes sql permettant de supprimer les tables de la base voie du projet F de correction des giratoires, rond-points, raquettes uni-tronçon.
*/

-- 1. Suppression des tables
DROP TABLE G_BASE_VOIE.TEMP_F_TRONCON CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_F_RELATION_VOIE_PHYSIQUE_ADMINISTRATIVE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_F_VOIE_PHYSIQUE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_F_VOIE_ADMINISTRATIVE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_F_LIBELLE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_F_TYPE_VOIE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_F_AGENT CASCADE CONSTRAINTS;

-- 2. Suppression des métadonnées spatiales
DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'TEMP_F_TRONCON';

-- 3. Suppression des séquences
DROP SEQUENCE SEQ_TEMP_F_TRONCON_OBJECTID;

COMMIT;