/*
Requêtes sql permettant de supprimer les tables de la base voie du projet G de correction de la latéralité des voies
*/

-- 1. Suppression des tables
DROP TABLE G_BASE_VOIE.TEMP_G_TRONCON CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_G_RELATION_VOIE_PHYSIQUE_ADMINISTRATIVE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_G_VOIE_PHYSIQUE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_G_VOIE_ADMINISTRATIVE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_G_LIBELLE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_G_TYPE_VOIE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_G_AGENT CASCADE CONSTRAINTS;

-- 2. Suppression des métadonnées spatiales
DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'TEMP_G_TRONCON';

-- 3. Suppression des séquences
DROP SEQUENCE SEQ_TEMP_G_TRONCON_OBJECTID;

COMMIT;