/*
Requêtes sql permettant de supprimer les tables de la base voie du projet i d''homogénéisation des latéralités par voie administrative.
*/

-- 1. Suppression des tables
DROP TABLE G_BASE_VOIE.TEMP_I_TRONCON CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_I_RELATION_VOIE_PHYSIQUE_ADMINISTRATIVE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_I_VOIE_PHYSIQUE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_I_VOIE_ADMINISTRATIVE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_I_LIBELLE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_I_TYPE_VOIE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_I_AGENT CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_I_HIERARCHISATION_VOIE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_I_RIVOLI CASCADE CONSTRAINTS;

-- 2. Suppression des métadonnées spatiales
DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'TEMP_I_TRONCON';

-- 3. Suppression des séquences
DROP SEQUENCE SEQ_TEMP_I_TRONCON_OBJECTID;

COMMIT;