/*
Requêtes sql permettant de supprimer les tables de la base voie du projet C permettant de corriger la latéralité des voies administratives de la base voie.
*/

-- 1. Suppression des tables
DROP TABLE G_BASE_VOIE.TEMP_C_TRONCON CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_C_RELATION_TRONCON_VOIE_PHYSIQUE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_C_RELATION_VOIE_PHYSIQUE_ADMINISTRATIVE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_C_VOIE_PHYSIQUE_VOIE_ADMINISTRATIVE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_C_VOIE_ADMINISTRATIVE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_C_LIBELLE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_C_TYPE_VOIE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_C_AGENT CASCADE CONSTRAINTS;

-- 2. Suppression des métadonnées spatiales
DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'TEMP_C_TRONCON';

-- 3. Suppression des séquences
DROP SEQUENCE SEQ_TEMP_C_TRONCON_OBJECTID;

COMMIT;