/*
Requêtes sql permettant de supprimer les tables de la base voie du projet H de correction des relations tronçons/seuils.
*/

-- 1. Suppression des tables
DROP TABLE G_BASE_VOIE.TEMP_H_TRONCON CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_H_RELATION_VOIE_PHYSIQUE_ADMINISTRATIVE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_H_VOIE_PHYSIQUE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_H_VOIE_ADMINISTRATIVE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_H_LIBELLE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_H_TYPE_VOIE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_H_AGENT CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_H_INFOS_SEUIL CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_H_SEUIL CASCADE CONSTRAINTS;

-- 2. Suppression des métadonnées spatiales
DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME IN('TEMP_H_TRONCON', 'TEMP_H_SEUIL');

-- 3. Suppression des séquences
DROP SEQUENCE SEQ_TEMP_H_TRONCON_OBJECTID;

COMMIT;