/*
Requêtes sql permettant de supprimer les tables de la base voie, servant à corriger les erreurs de topologie de la base voie.
*/

-- 1. Suppression des tables
DROP TABLE G_BASE_VOIE.TEMP_B_TRONCON CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_B_RELATION_TRONCON_VOIE_PHYSIQUE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_B_VOIE_PHYSIQUE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_B_VOIE_ADMINISTRATIVE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_B_LIBELLE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_B_TYPE_VOIE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TEMP_B_AGENT CASCADE CONSTRAINTS;

-- 2. Suppression des métadonnées spatiales
DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'TEMP_B_TRONCON';

-- 3. Suppression des séquences
DROP SEQUENCE SEQ_TEMP_B_TRONCON_OBJECTID;

-- 4. Suppression des fonctions
COMMIT;