/*
Suppression de tous les objets du projet LITTERALIS présents sur le schéma G_BASE_VOIE + les éléments issus de G_VOIRIE et nécessaires au projet
*/

-- Suppression des vues
DROP VIEW G_BASE_VOIE.V_LITTERALIS_AUDIT_TRONCON;
DROP VIEW G_BASE_VOIE.V_LITTERALIS_AUDIT_ADRESSE;
DROP VIEW G_BASE_VOIE.V_LITTERALIS_AUDIT_ZONE_PARTICULIERE;
DROP VIEW G_BASE_VOIE.V_LITTERALIS_TRONCON;
DROP VIEW G_BASE_VOIE.V_LITTERALIS_ADRESSE;
DROP VIEW G_BASE_VOIE.V_LITTERALIS_REGROUPEMENT;
DROP VIEW G_BASE_VOIE.V_LITTERALIS_ZONE_PARTICULIERE;

-- Suppresion des vues matérialisées
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_INFORMATION_VOIE_LITTERALIS;
DROP INDEX VM_TAMPON_LITTERALIS_ZONE_PARTICULIERE_INTERSECT_HORS_AGGLO_SIDX;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_TAMPON_LITTERALIS_ZONE_PARTICULIERE_INTERSECT_HORS_AGGLO;
DROP INDEX VM_TAMPON_LITTERALIS_ZONE_PARTICULIERE_INTERSECT_AGGLO_SIDX;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_TAMPON_LITTERALIS_ZONE_PARTICULIERE_INTERSECT_AGGLO;
DROP INDEX VM_TAMPON_LITTERALIS_ZONE_PARTICULIERE_HORS_AGGLO_SIDX;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_TAMPON_LITTERALIS_ZONE_PARTICULIERE_HORS_AGGLO;
DROP INDEX VM_TAMPON_LITTERALIS_ZONE_PARTICULIERE_EN_AGGLO_SIDX;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_TAMPON_LITTERALIS_ZONE_PARTICULIERE_EN_AGGLO;
DROP INDEX VM_TAMPON_LITTERALIS_ZONE_AGGLOMERATION_SIDX;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_TAMPON_LITTERALIS_ZONE_AGGLOMERATION;
DROP INDEX VM_TAMPON_LITTERALIS_REGROUPEMENT_SIDX;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_TAMPON_LITTERALIS_REGROUPEMENT;
DROP INDEX VM_UNITE_TERRITORIALE_VOIRIE_SIDX;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_UNITE_TERRITORIALE_VOIRIE;
DROP INDEX VM_TERRITOIRE_VOIRIE_SIDX;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_TERRITOIRE_VOIRIE;
DROP INDEX VM_TAMPON_LITTERALIS_ADRESSE_SIDX;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_TAMPON_LITTERALIS_ADRESSE;
DROP INDEX VM_TAMPON_LITTERALIS_TRONCON_SIDX;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_TAMPON_LITTERALIS_TRONCON;
DROP INDEX VM_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE_SIDX;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_TAMPON_LITTERALIS_CORRESPONDANCE_DOMANIALITE_CLASSEMENT;

-- Suppression des tables
DROP TABLE G_BASE_VOIE.TA_SECTEUR_VOIRIE CASCADE CONSTRAINTS;

-- Suppression des métadonnées spatiales
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'VM_TAMPON_LITTERALIS_ZONE_PARTICULIERE_INTERSECT_HORS_AGGLO';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'VM_TAMPON_LITTERALIS_ZONE_PARTICULIERE_INTERSECT_AGGLO';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'VM_TAMPON_LITTERALIS_ZONE_PARTICULIERE_HORS_AGGLO';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'VM_TAMPON_LITTERALIS_ZONE_PARTICULIERE_EN_AGGLO';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'VM_TAMPON_LITTERALIS_ZONE_AGGLOMERATION';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'VM_TAMPON_LITTERALIS_REGROUPEMENT';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'VM_UNITE_TERRITORIALE_VOIRIE';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'VM_TERRITOIRE_VOIRIE';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'VM_TAMPON_LITTERALIS_ADRESSE';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'VM_TAMPON_LITTERALIS_TRONCON';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'VM_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_SECTEUR_VOIRIE';

COMMIT;