/*
Suppression des vues matérialisées et de leur métadonnée spatiale
*/
-- 1. Vues matérialisées de consultation, audit et statistiques
-- 1.1. Suppression des index spatiaux des VM de consultation
DROP INDEX VM_CONSULTATION_BASE_VOIE;
DROP INDEX VM_CONSULTATION_SEUIL;
DROP INDEX VM_CONSULTATION_VOIE_ADMINISTRATIVE;
DROP INDEX VM_CONSULTATION_VOIE_PHYSIQUE;
DROP INDEX VM_CONSULTATION_VOIE_SUPRA_COMMUNALE;

-- 1.2. Suppression des VM de consultation
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_CONSULTATION_BASE_VOIE;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_CONSULTATION_SEUIL;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_CONSULTATION_VOIE_ADMINISTRATIVE;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_CONSULTATION_VOIE_PHYSIQUE;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_CONSULTATION_VOIE_SUPRA_COMMUNALE;

-- 1.3. Supression des index spatiaux des VM d'audit
DROP INDEX VM_AUDIT_DISTANCE_SEUIL_TRONCON_1KM_SIDX;
DROP INDEX VM_AUDIT_DOUBLON_NUMERO_SEUIL_PAR_VOIE_ADMINISTRATIVE_SIDX;
DROP INDEX VM_AUDIT_CODE_INSEE_SEUIL_EN_ERREUR_SIDX;
DROP INDEX VM_AUDIT_TRONCON_NON_JOINTIFS_SIDX;

-- 1.4. Suppression des VM d'audit
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_AUDIT_DISTANCE_SEUIL_TRONCON_1KM;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_AUDIT_DOUBLON_NUMERO_SEUIL_PAR_VOIE_ADMINISTRATIVE;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_AUDIT_CODE_INSEE_SEUIL_EN_ERREUR;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_AUDIT_TRONCON_NON_JOINTIFS;

-- 2. Suppression des métadonnées spatiales
DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'VM_CONSULTATION_VOIE_ADMINISTRATIVE';

DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'VM_CONSULTATION_BASE_VOIE';

DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'VM_CONSULTATION_SEUIL';

DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'VM_CONSULTATION_VOIE_PHYSIQUE';

DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'VM_CONSULTATION_VOIE_SUPRA_COMMUNALE';

DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'VM_AUDIT_CODE_INSEE_SEUIL_EN_ERREUR';

DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'VM_AUDIT_DISTANCE_SEUIL_TRONCON_1KM';

DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'VM_AUDIT_DOUBLON_NUMERO_SEUIL_PAR_VOIE_ADMINISTRATIVE';

DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'VM_AUDIT_TRONCON_NON_JOINTIFS';

COMMIT;