/*
Requêtes sql permettant de supprimer les tables de la base voie avec leur MTD spatiale, index, contraintes, triggers et fonctions.
*/

-- 1. Suppression des tables pivot
DROP TABLE G_BASE_VOIE.TA_HIERARCHISATION_VOIE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_RELATION_VOIE_PHYSIQUE_ADMINISTRATIVE CASCADE CONSTRAINTS;

-- 2. Suppression des tables de logs
DROP TABLE G_BASE_VOIE.TA_RELATION_VOIE_PHYSIQUE_ADMINISTRATIVE_LOG CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_TRONCON_LOG CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_VOIE_PHYSIQUE_LOG CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_VOIE_ADMINISTRATIVE_LOG CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_SEUIL_LOG CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_INFOS_SEUIL_LOG CASCADE CONSTRAINTS;

-- 3. Suppression des autres tables
DROP TABLE G_BASE_VOIE.TA_TYPE_VOIE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_LIBELLE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_AGENT CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_RIVOLI CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_VOIE_ADMINISTRATIVE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_VOIE_PHYSIQUE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_TRONCON CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_INFOS_SEUIL CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_SEUIL CASCADE CONSTRAINTS;

-- 4. Suppression des vues/VM de consultation, audit et statistiques
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_CONSULTATION_BASE_VOIE;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_CONSULTATION_SEUIL;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_CONSULTATION_VOIE_ADMINISTRATIVE;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_CONSULTATION_VOIE_PHYSIQUE;

## Vues/VM d'audit
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_AUDIT_DISTANCE_SEUIL_TRONCON_1KM;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_AUDIT_DOUBLON_NOM_VOIE_PAR_COMMUNE;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_AUDIT_DOUBLON_NUMERO_SEUIL_PAR_VOIE_ADMINISTRATIVE;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_AUDIT_CODE_INSEE_SEUIL_EN_ERREUR;

## Vues/VM de stats
DROP VIEW G_BASE_VOIE.V_STAT_NOMBRE_OBJET
DROP VIEW G_BASE_VOIE.V_STAT_NOMBRE_VOIE_ADMINISTRATIVE_PAR_NOMBRE_VOIE_PHYSIQUE
DROP VIEW G_BASE_VOIE.V_STAT_NOMBRE_SEUIL_PAR_GEOMETRIE
DROP VIEW G_BASE_VOIE.V_AUDIT_CREATION_OBJET_PAR_ANNEE_MOIS

## Vues/VM de gestion du schéma
DROP VIEW G_BASE_VOIE.V_ADMIN_FREQUENCE_MAJ_VUE_MATERIALISEE

-- 5. Suppression des métadonnées spatiales
DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'TA_TRONCON';

DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'TA_TRONCON_LOG';

DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'TA_SEUIL';

DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'TA_SEUIL_LOG';

DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'VM_AUDIT_DISTANCE_SEUIL_TRONCON_1KM';

DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'VM_AUDIT_DOUBLON_NOM_VOIE_PAR_COMMUNE';

DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'VM_AUDIT_DOUBLON_NUMERO_SEUIL_PAR_VOIE_ADMINISTRATIVE';

DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'VM_CONSULTATION_SEUIL';

DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'VM_CONSULTATION_BASE_VOIE;';

DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'VM_CONSULTATION_VOIE_ADMINISTRATIVE';

DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'VM_CONSULTATION_VOIE_PHYSIQUE';

-- 6. Suppression des fonctions personnalisées
/*DROP FUNCTION G_BASE_VOIE.GET_CODE_INSEE_97_COMMUNES_CONTAIN_LINE;
DROP FUNCTION G_BASE_VOIE.GET_CODE_INSEE_97_COMMUNES_POURCENTAGE;
DROP FUNCTION G_BASE_VOIE.GET_CODE_INSEE_97_COMMUNES_TRONCON;
DROP FUNCTION G_BASE_VOIE.GET_CODE_INSEE_97_COMMUNES_WITHIN_DISTANCE;
DROP FUNCTION G_BASE_VOIE.GET_CODE_INSEE_CONTAIN_LINE;
DROP FUNCTION G_BASE_VOIE.GET_CODE_INSEE_CONTAIN_POINT;
DROP FUNCTION G_BASE_VOIE.GET_CODE_INSEE_POURCENTAGE;
DROP FUNCTION G_BASE_VOIE.GET_CODE_INSEE_TRONCON;
DROP FUNCTION G_BASE_VOIE.GET_CODE_INSEE_WITHIN_DISTANCE;
*/
-- 7. Suppression des vues matérialisées
/*
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_VOIE_AGGREGEE;
DROP MATERIALIZED VIEW G_BASE_VOIE.VM_GRU_ADRESSE;

-- 8. Suppression des vues
DROP VIEW G_BASE_VOIE.V_TRONCON_VOIE_GRU;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'V_TRONCON_VOIE_GRU';
*/
-- 9. Suppression des séquences
DROP SEQUENCE SEQ_TA_TRONCON_OBJECTID;
DROP SEQUENCE SEQ_TA_VOIE_PHYSIQUE_OBJECTID;
COMMIT;

--ALTER TABLE G_BASE_VOIE.TEMP_VOIEVOI DROP COLUMN temp_code_fantoir;