/*
Création de la table temporaire TEMP_BUFFER_SEUIL dans laquelle seront enregistrés tous les buffers de 10cm autours des seuils.
Cette table servira à ne conserver qu'un seul seuil si plusieurs seuils se trouvent dans un rayon de 10cm, l'objectif étant d'avoir un seul point géographique pour plusieurs seuils.
*/

CREATE TABLE G_BASE_VOIE.TEMP_BUFFER_SEUIL(
    IDSEUI NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY,
    GEOM SDO_GEOMETRY
);    
COMMENT ON TABLE G_BASE_VOIE.TEMP_BUFFER_SEUIL IS 'Table temporaire dans laquelle se trouvent les buffers de 10cm autours de chaque seuil.';

-- 3. Création de la clé primaire
ALTER TABLE G_BASE_VOIE.TEMP_BUFFER_SEUIL 
ADD CONSTRAINT TEMP_BUFFER_SEUIL_PK 
PRIMARY KEY("IDSEUI") 
USING INDEX TABLESPACE "G_ADT_INDX";

-- 4. Création des métadonnées spatiales
INSERT INTO USER_SDO_GEOM_METADATA(
    TABLE_NAME, 
    COLUMN_NAME, 
    DIMINFO, 
    SRID
)
VALUES(
    'TEMP_BUFFER_SEUIL',
    'geom',
    SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 684540, 719822.2, 0.005),SDO_DIM_ELEMENT('Y', 7044212, 7078072, 0.005)), 
    2154
);


-- 5. Création de l'index spatial sur le champ geom
CREATE INDEX TEMP_BUFFER_SEUIL_SIDX
ON G_BASE_VOIE.TEMP_BUFFER_SEUIL(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2, layer_gtype=POLYGON, tablespace=G_ADT_INDX, work_tablespace=DATA_TEMP');