/*
Désactivation des contraintes et suppression des index des tables tampon du projet LITTERALIS dans le cadre de leur remplissage
*/
CREATE OR REPLACE PROCEDURE DESACTIVATION_SUPPRESSION_CONTRAINTE_INDEX_TABLE_TAMPON_LITTERALIS AS
BEGIN
    -- Objectif : désactiver toutes les contraintes et supprimer tous les index des tables tampon du projet LITTERALIS.
    
-- Désactivation des contraintes

-- Suppression des index
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_ADRESSE_SIDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_ADRESSE_CODE_POINT_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_ADRESSE_CODE_VOIE_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_ADRESSE_NATURE_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_ADRESSE_LIBELLE_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_ADRESSE_NUMERO_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_ADRESSE_REPETITION_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_CORRESPONDANCE_DOMANIALITE_CLASSEMENT_DOMANIALITE_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_CORRESPONDANCE_DOMANIALITE_CLASSEMENT_CLASSEMENT_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_SECTEUR_SIDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_SECTEUR_NOM_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_TERRITOIRE_SIDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_TERRITOIRE_NOM_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_TRONCON_CODE_TRONCON_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_TRONCON_CLASSEMENT_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_TRONCON_ID_VOIE_DROITE_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_TRONCON_ID_VOIE_GAUCHE_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_TRONCON_CODE_INSEE_VOIE_DROITE_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_TRONCON_CODE_INSEE_VOIE_GAUCHE_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_TRONCON_NOM_VOIE_DROITE_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_TRONCON_NOM_VOIE_GAUCHE_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_TRONCON_SIDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_UNITE_TERRITORIALE_SIDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_UNITE_TERRITORIALE_NOM_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_VOIE_SIDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_VOIE_CODE_VOIE_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_VOIE_NOM_VOIE_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_VOIE_CODE_INSEE_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_VOIE_ID_VOIE_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_VOIE_COTE_VOIE_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE_SIDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE_CODE_VOIE_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE_NOM_VOIE_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_VOIE_ADMINISTRATIVE_CODE_INSEE_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_ZONE_AGGLOMERATION_SIDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_ZONE_PARTICULIERE_SIDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_ZONE_PARTICULIERE_CODE_VOIE_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_ZONE_PARTICULIERE_CATEGORIE_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_ZONE_PARTICULIERE_COTE_VOIE_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_ZONE_PARTICULIERE_CODE_INSEE_IDX';
EXECUTE IMMEDIATE 'DROP INDEX TA_TAMPON_LITTERALIS_ZONE_PARTICULIERE_ID_VOIE_IDX';

 -- En cas d'erreur une exception est levée et un rollback effectué, empêchant ainsi toute insertion de se faire et de retourner à l'état des tables précédent l'insertion.
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE(' L''erreur ' || SQLCODE || 'est survenue. ' || SQLERRM(SQLCODE));
END;

